### ISSUE TITLE
Tag-110-Sever-Java Error When User Logging out From Server

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#120]
Steps to reproduce:
1) Launch protege server and client
2) Log into the Server "https://nciws-d699-v.nci.nih.gov:9090" used "root" login
3) Click "Server" top browser to log out then you'll see the java error. 
 Please see attached screen shots and log file for more details.
 Thanks,
 Reza
![tag110-login page1](https://cloud.githubusercontent.com/assets/8367102/21031980/6f17afa0-bd74-11e6-9481-89a2fbb1d697.png)
![tag110-login page2](https://cloud.githubusercontent.com/assets/8367102/21031982/76583780-bd74-11e6-9f1b-669b56393a6e.png)
[Server_Logout_Error_Root User.txt](https://github.com/NCIEVS/nci-protege5/files/642220/Server_Logout_Error_Root.User.txt)

**Comment by bdionne** [comment]
I"m confused, what is the error? You can't logout?

**Comment by rmehri** [comment]
Yes when click on logout link  the java error occurs.  I have already attached it to this ticket.  

BAD ViewComponent: (NCIEditViewComponent) Exception on dispose: null
Disposed of NCI Edit Tab
Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.ArrayIndexOutOfBoundsException: -1
        at javax.swing.plaf.basic.BasicTabbedPaneUI.getTabBounds(BasicTabbedPane
UI.java:1534) ~[na:1.8.0_101]
        at javax.swing.plaf.basic.BasicTabbedPaneUI.getTabBounds(BasicTabbedPane
UI.java:1469) ~[na:1.8.0_101]
        at org.protege.editor.core.ui.tabbedpane.CloseableTabbedPaneUI.getTabBou
nds(CloseableTabbedPaneUI.java:266) ~[na:na]
        at org.protege.editor.core.ui.tabbedpane.CloseableTabbedPaneUI.paintCont
entBorderTopEdge(CloseableTabbedPaneUI.java:397) ~[na:na]
        at javax.swing.plaf.basic.BasicTabbedPaneUI.paintContentBorder(BasicTabb
edPaneUI.java:1315) ~[na:1.8.0_101]
        at javax.swing.plaf.basic.BasicTabbedPaneUI.paint(BasicTabbedPaneUI.java
:800) ~[na:1.8.0_101]
        at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161) ~[na:1.8.0_
101]
        at javax.swing.JComponent.paintComponent(JComponent.java:780) ~[na:1.8.0
_101]
        at javax.swing.JComponent.paint(JComponent.java:1056) ~[na:1.8.0_101]
        at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[na:1.8.0_
101]
        at javax.swing.JSplitPane.paintChildren(JSplitPane.java:1047) ~[na:1.8.0
_101]
        at javax.swing.JComponent.paint(JComponent.java:1065) ~[na:1.8.0_101]
        at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[na:1.8.0_
101]
        at javax.swing.JSplitPane.paintChildren(JSplitPane.java:1047) ~[na:1.8.0
_101]
        at javax.swing.JComponent.paint(JComponent.java:1065) ~[na:1.8.0_101]
        at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[na:1.8.0_
101]
        at javax.swing.JComponent.paint(JComponent.java:1065) ~[na:1.8.0_101]
        at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[na:1.8.0_
101]
        at javax.swing.JComponent.paint(JComponent.java:1065) ~[na:1.8.0_101]
        at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[na:1.8.0_
101]
        at javax.swing.JComponent.paint(JComponent.java:1065) ~[na:1.8.0_101]
        at javax.swing.JLayeredPane.paint(JLayeredPane.java:586) ~[na:1.8.0_101]

        at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[na:1.8.0_
101]
        at javax.swing.JComponent.paint(JComponent.java:1065) ~[na:1.8.0_101]
        at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210) ~[na:1.
8.0_101]
        at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintMa
nager.java:1579) ~[na:1.8.0_101]
        at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:150
2) ~[na:1.8.0_101]
        at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManag
er.java:306) ~[na:1.8.0_101]
        at javax.swing.RepaintManager.paint(RepaintManager.java:1272) ~[na:1.8.0
_101]
        at javax.swing.JComponent._paintImmediately(JComponent.java:5158) ~[na:1
.8.0_101]
        at javax.swing.JComponent.paintImmediately(JComponent.java:4969) ~[na:1.
8.0_101]
        at javax.swing.RepaintManager$4.run(RepaintManager.java:831) ~[na:1.8.0_
101]
        at javax.swing.RepaintManager$4.run(RepaintManager.java:814) ~[na:1.8.0_
101]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0
_101]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(ProtectionDomain.java:76) ~[na:1.8.0_101]
        at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
 ~[na:1.8.0_101]
        at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
 ~[na:1.8.0_101]
        at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:7
38) ~[na:1.8.0_101]
        at javax.swing.RepaintManager.access$1200(RepaintManager.java:64) ~[na:1
.8.0_101]
        at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java
:1732) ~[na:1.8.0_101]
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[n
a:1.8.0_101]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756) ~[na:1.8.0
_101]
        at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_101]
        at java.awt.EventQueue$3.run(EventQueue.java:709) ~[na:1.8.0_101]
        at java.awt.EventQueue$3.run(EventQueue.java:703) ~[na:1.8.0_101]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0
_101]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(ProtectionDomain.java:76) ~[na:1.8.0_101]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726) ~[na:1.8.0_101
]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThre
ad.java:201) [na:1.8.0_101]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.
java:116) [na:1.8.0_101]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThre
ad.java:105) [na:1.8.0_101]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 [na:1.8.0_101]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
[na:1.8.0_101]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8
.0_101]





Thna
Thnka

**Comment by bdionne** [comment]
Yes, thanks @rmehri, I saw the exception. My question is what is the behavior? Does the app fail for you in some way? Are you unable to log back in? Sometime exceptions, though not ideal, are largely harmless.

**Comment by rmehri** [comment]
No. I have end the session and run the client again to login the server. Thanks, Reza

**Comment by rmehri** [comment]
Hi,
The logout from server error still occurs. Please see attached log file.
[Logged out from server.txt](https://github.com/NCIEVS/nci-protege5/files/930682/Logged.out.from.server.txt)

 Thanks,
Reza

**Comment by bdionne** [comment]
Thanks Reza, we can discuss and screen share at some point. We're closing this for now. @NCIEVS and I are going through the issues list and closing tickets against old release and/or not reproducible on the current builds
