### ISSUE TITLE
Interpret the absence of a data type on a property to mean xsd:string

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#16]
When an annotation property has no data type, null pointers occur. Treat the absence of a type to mean a text box

```
java.lang.NullPointerException: null
        at gov.nih.nci.ui.PropertyTableModel.isDataTypeTextArea(PropertyTableModel.java:193) ~[na:na]
        at gov.nih.nci.ui.PropertyTableModel.getSelectedPropertyType(PropertyTableModel.java:136) ~[na:na]
        at gov.nih.nci.ui.PropertyTablePanel.actionPerformed(PropertyTablePanel.java:188) ~[na:na]
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) ~[na:1.8.0_91]
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) ~[na:1.8.0_91]
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) ~[na:1.8.0_91]
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source) ~[na:1.8.0_91]
```

**Comment by NCIEVS** [comment]
Adding an explanation for this enhancement in the [wiki](https://github.com/NCIEVS/nci-protege5/wiki/declaration-of-annotation-property-ranges-and-specifying-datatypes-in-annotations-on-classes).  This one is ready for QA.

**Comment by rmehri** [comment]
Hi, 
Can you please elaborate more with an example for this issue? So I can verify the fix.

Thanks,
Reza

**Comment by bdionne** [comment]
when the datatype of the property is not specified, then it should be interpreted as a string. So, .eg. when editing that property the widget should render it as a text field and not a text area

**Comment by rmehri** [comment]
Hi Bob, 
Thanks for your feedback! Based on your feedback, I  have retested this issue using tag 116 and did not receive any error.  Meanwhile, please see attached screen shot for more detail.
Thanks,
Reza
![datatype1](https://cloud.githubusercontent.com/assets/8367102/21861988/565c09a6-d805-11e6-9297-80fc85d74aa3.png)
