### ISSUE TITLE
pellet exception when requesting explanations

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#176]
classification done on the server, subsequently an explanation was requested (from the "?" icon) and the following exception was thrown on the client.

Jan 10, 2017 4:14:44 PM com.clarkparsia.owlapi.explanation.GlassBoxExplanation g
etExplanation
SEVERE: Unexpected error while trying to get explanation set from Pellet
org.semanticweb.owlapi.model.OWLRuntimeException: No explanation computed
        at com.clarkparsia.owlapi.explanation.GlassBoxExplanation.convertExplanation(GlassBoxExplanation.java:263)
        at com.clarkparsia.owlapi.explanation.GlassBoxExplanation.getPelletExplanation(GlassBoxExplanation.java:233)
        at com.clarkparsia.owlapi.explanation.GlassBoxExplanation.getExplanation(GlassBoxExplanation.java:204)
        at com.clarkparsia.owlapi.explanation.HSTExplanationGenerator.getExplanation(HSTExplanationGenerator.java:110)
        at com.clarkparsia.owlapi.explanation.HSTExplanationGenerator.getExplanations(HSTExplanationGenerator.java:131)
        at com.clarkparsia.owlapi.explanation.PelletExplanation.getUnsatisfiableExplanations(PelletExplanation.java:180)
        at com.clarkparsia.owlapi.explanation.PelletExplanation.getEntailmentExplanations(PelletExplanation.java:94)
        at com.clarkparsia.pellet.protege.PelletExplanationService.explainInference(PelletExplanationService.java:121)
        at com.clarkparsia.pellet.protege.PelletExplanationService.getExplanations(PelletExplanationService.java:102)
        at com.clarkparsia.pellet.protege.PelletExplanationService.explain(PelletExplanationService.java:91)
        at org.protege.editor.owl.ui.explanation.ExplanationDialog.<init>(ExplanationDialog.java:32)
        at org.protege.editor.owl.ui.explanation.ExplanationManager.handleExplain(ExplanationManager.java:84)
        at org.protege.editor.owl.ui.framelist.OWLFrameList.invokeExplanationHandler(OWLFrameList.java:563)
        at org.protege.editor.owl.ui.framelist.OWLFrameList.lambda$new$1(OWLFrameList.java:191)
        at org.protege.editor.core.ui.list.MList.handleMouseClick(MList.java:206)
        at org.protege.editor.core.ui.list.MList.access$200(MList.java:21)
        at org.protege.editor.core.ui.list.MList$3.mouseReleased(MList.java:104)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

org.semanticweb.owlapi.model.OWLRuntimeException: org.semanticweb.owlapi.model.OWLRuntimeException: No explanation computed
        at com.clarkparsia.owlapi.explanation.GlassBoxExplanation.getExplanation(GlassBoxExplanation.java:209)
        at com.clarkparsia.owlapi.explanation.HSTExplanationGenerator.getExplanation(HSTExplanationGenerator.java:110)
        at com.clarkparsia.owlapi.explanation.HSTExplanationGenerator.getExplanations(HSTExplanationGenerator.java:131)
        at com.clarkparsia.owlapi.explanation.PelletExplanation.getUnsatisfiableExplanations(PelletExplanation.java:180)
        at com.clarkparsia.owlapi.explanation.PelletExplanation.getEntailmentExplanations(PelletExplanation.java:94)
        at com.clarkparsia.pellet.protege.PelletExplanationService.explainInference(PelletExplanationService.java:121)
        at com.clarkparsia.pellet.protege.PelletExplanationService.getExplanations(PelletExplanationService.java:102)
        at com.clarkparsia.pellet.protege.PelletExplanationService.explain(PelletExplanationService.java:91)
        at org.protege.editor.owl.ui.explanation.ExplanationDialog.<init>(ExplanationDialog.java:32)
        at org.protege.editor.owl.ui.explanation.ExplanationManager.handleExplain(ExplanationManager.java:84)
        at org.protege.editor.owl.ui.framelist.OWLFrameList.invokeExplanationHandler(OWLFrameList.java:563)
        at org.protege.editor.owl.ui.framelist.OWLFrameList.lambda$new$1(OWLFrameList.java:191)
        at org.protege.editor.core.ui.list.MList.handleMouseClick(MList.java:206)
        at org.protege.editor.core.ui.list.MList.access$200(MList.java:21)
        at org.protege.editor.core.ui.list.MList$3.mouseReleased(MList.java:104)

        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: org.semanticweb.owlapi.model.OWLRuntimeException: No explanation computed
        at com.clarkparsia.owlapi.explanation.GlassBoxExplanation.convertExplanation(GlassBoxExplanation.java:263)
        at com.clarkparsia.owlapi.explanation.GlassBoxExplanation.getPelletExplanation(GlassBoxExplanation.java:233)
        at com.clarkparsia.owlapi.explanation.GlassBoxExplanation.getExplanation(GlassBoxExplanation.java:204)
        ... 48 more
Uncaught Exception in thread 'AWT-EventQueue-0'
org.semanticweb.owlapi.model.OWLRuntimeException: org.semanticweb.owlapi.model.OWLRuntimeException: No explanation computed
        at com.clarkparsia.owlapi.explanation.GlassBoxExplanation.getExplanation(GlassBoxExplanation.java:209) ~[na:na]
        at com.clarkparsia.owlapi.explanation.HSTExplanationGenerator.getExplanation(HSTExplanationGenerator.java:110) ~[na:na]
        at com.clarkparsia.owlapi.explanation.HSTExplanationGenerator.getExplanations(HSTExplanationGenerator.java:131) ~[na:na]
        at com.clarkparsia.owlapi.explanation.PelletExplanation.getUnsatisfiableExplanations(PelletExplanation.java:180) ~[na:na]
        at com.clarkparsia.owlapi.explanation.PelletExplanation.getEntailmentExplanations(PelletExplanation.java:94) ~[na:na]
        at com.clarkparsia.pellet.protege.PelletExplanationService.explainInference(PelletExplanationService.java:121) ~[na:na]
        at com.clarkparsia.pellet.protege.PelletExplanationService.getExplanations(PelletExplanationService.java:102) ~[na:na]
        at com.clarkparsia.pellet.protege.PelletExplanationService.explain(PelletExplanationService.java:91) ~[na:na]
        at org.protege.editor.owl.ui.explanation.ExplanationDialog.<init>(ExplanationDialog.java:32) ~[na:na]
        at org.protege.editor.owl.ui.explanation.ExplanationManager.handleExplain(ExplanationManager.java:84) ~[na:na]
        at org.protege.editor.owl.ui.framelist.OWLFrameList.invokeExplanationHandler(OWLFrameList.java:563) ~[na:na]
        at org.protege.editor.owl.ui.framelist.OWLFrameList.lambda$new$1(OWLFrameList.java:191) ~[na:na]
        at org.protege.editor.core.ui.list.MList.handleMouseClick(MList.java:206) ~[na:na]
        at org.protege.editor.core.ui.list.MList.access$200(MList.java:21) ~[na:na]
        at org.protege.editor.core.ui.list.MList$3.mouseReleased(MList.java:104)~[na:na]
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source) ~[na:1.8.0_102]
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source) ~[na:1.8.0_102]
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.processMouseEvent(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.JComponent.processMouseEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.processEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Container.processEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.dispatchEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Window.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.dispatchEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventQueue.access$500(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventQueue$3.run(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventQueue$3.run(Unknown Source) ~[na:1.8.0_102]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_102]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[na:1.8.0_102]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventQueue$4.run(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventQueue$4.run(Unknown Source) ~[na:1.8.0_102]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_102]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [na:1.8.0_102]
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [na:1.8.0_102]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [na:1.8.0_102]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_102]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_102]
        at java.awt.EventDispatchThread.run(Unknown Source) [na:1.8.0_102]
Caused by: org.semanticweb.owlapi.model.OWLRuntimeException: No explanation computed
        at com.clarkparsia.owlapi.explanation.GlassBoxExplanation.convertExplanation(GlassBoxExplanation.java:263) ~[na:na]
        at com.clarkparsia.owlapi.explanation.GlassBoxExplanation.getPelletExplanation(GlassBoxExplanation.java:233) ~[na:na]
        at com.clarkparsia.owlapi.explanation.GlassBoxExplanation.getExplanation
(GlassBoxExplanation.java:204) ~[na:na]
        ... 48 common frames omitted

**Comment by bdionne** [comment]
part of #204

**Comment by NCIEVS** [comment]
This is fixed.  Tested in RC 2.1.010.
