### ISSUE TITLE
failure to export concept history

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#177]
After a "prompt" session, the "export history" button was pressed on the "revision" tab.  Exceptions were thrown on the client and the server.  The "prompt" session was being conducted remotely over VPN.

Client exception
------------------
Server failed to generate concept history (contact server admin for further assistance)
org.protege.editor.owl.client.api.exception.ClientRequestException: Server failed to generate concept history (contact server admin for further assistance)
        at org.protege.editor.owl.client.LocalHttpClient.throwRequestExceptions(LocalHttpClient.java:720) ~[protege-client-3.0.0-SNAPSHOT.jar:na]
        at org.protege.editor.owl.client.LocalHttpClient.get(LocalHttpClient.java:603) ~[protege-client-3.0.0-SNAPSHOT.jar:na]
        at org.protege.editor.owl.client.LocalHttpClient.genConceptHistory(LocalHttpClient.java:681) ~[protege-client-3.0.0-SNAPSHOT.jar:na]
        at org.protege.editor.owl.client.diff.ui.ReviewButtonsPanel$6.actionPerformed(ReviewButtonsPanel.java:174) [protege-client-3.0.0-SNAPSHOT.jar:na]
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) [na:1.8.0_102]
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) [na:1.8.0_102]
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) [na:1.8.0_102]
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source) [na:1.8.0_102]
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source) [na:1.8.0_102]
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source) [na:1.8.0_102]
        at java.awt.Component.processMouseEvent(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.processMouseEvent(Unknown Source) [na:1.8.0_102]
        at java.awt.Component.processEvent(Unknown Source) [na:1.8.0_102]
        at java.awt.Container.processEvent(Unknown Source) [na:1.8.0_102]
        at java.awt.Component.dispatchEventImpl(Unknown Source) [na:1.8.0_102]
        at java.awt.Container.dispatchEventImpl(Unknown Source) [na:1.8.0_102]
        at java.awt.Component.dispatchEvent(Unknown Source) [na:1.8.0_102]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) [na:1.8.0_102]
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) [na:1.8.0_102]
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) [na:1.8.0_102]
        at java.awt.Container.dispatchEventImpl(Unknown Source) [na:1.8.0_102]
        at java.awt.Window.dispatchEventImpl(Unknown Source) [na:1.8.0_102]
        at java.awt.Component.dispatchEvent(Unknown Source) [na:1.8.0_102]
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [na:1.8.0_102]
        at java.awt.EventQueue.access$500(Unknown Source) [na:1.8.0_102]
        at java.awt.EventQueue$3.run(Unknown Source) [na:1.8.0_102]
        at java.awt.EventQueue$3.run(Unknown Source) [na:1.8.0_102]
        at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_102]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [na:1.8.0_102]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [na:1.8.0_102]
        at java.awt.EventQueue$4.run(Unknown Source) [na:1.8.0_102]
        at java.awt.EventQueue$4.run(Unknown Source) [na:1.8.0_102]
        at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_102]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [na:1.8.0_102]
        at java.awt.EventQueue.dispatchEvent(Unknown Source) [na:1.8.0_102]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [na:1.8.0_102]
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [na:1.8.0_102]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [na:1.8.0_102]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_102]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_102]
        at java.awt.EventDispatchThread.run(Unknown Source) [na:1.8.0_102]
org.protege.editor.owl.client.api.exception.ClientRequestException: Failed to successfuly generate concept history.
        at org.protege.editor.owl.client.LocalHttpClient.genConceptHistory(LocalHttpClient.java:685)
        at org.protege.editor.owl.client.diff.ui.ReviewButtonsPanel$6.actionPerformed(ReviewButtonsPanel.java:174)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: org.protege.editor.owl.client.api.exception.ClientRequestException: Server failed to generate concept history (contact server admin for further assistance)
        at org.protege.editor.owl.client.LocalHttpClient.throwRequestExceptions(LocalHttpClient.java:720)
        at org.protege.editor.owl.client.LocalHttpClient.get(LocalHttpClient.java:603)
        at org.protege.editor.owl.client.LocalHttpClient.genConceptHistory(LocalHttpClient.java:681)
        ... 38 more

Server exception
------------------
16:20:59 [XNIO-1 task-1] ERROR - null
java.lang.NullPointerException: null
        at java.io.FileOutputStream.<init>(FileOutputStream.java:203) ~[na:1.8.0_112]
        at java.io.FileOutputStream.<init>(FileOutputStream.java:101) ~[na:1.8.0_112]
        at java.io.FileWriter.<init>(FileWriter.java:63) ~[na:1.8.0_112]
        at org.protege.editor.owl.server.http.handlers.CodeGenHandler.generateConceptHistory(CodeGenHandler.java:177) ~[org.protege.owl.server.jar:na]
        at org.protege.editor.owl.server.http.handlers.CodeGenHandler.handlingRequest(CodeGenHandler.java:119) ~[org.protege.owl.server.jar:na]
        at org.protege.editor.owl.server.http.handlers.CodeGenHandler.handleRequest(CodeGenHandler.java:45) ~[org.protege.owl.server.jar:na]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:198) [undertow-core.jar:1.3.4.Final]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:788) [undertow-core.jar:1.3.4.Final]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_112]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_112]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_112]

**Comment by NCIEVS** [comment]
The project had not yet been configured with a key-value pair for the concept history export.  Will need to be re-examined.  The server now has the following key-value:
 "conhistory_file": "concept_history"
