### ISSUE TITLE
failure to create new project

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#178]
This was done remotely, so perhaps the timeout was set too low.  Also, the remote client was memory-constrained.  The failure/exception happened when the OWL file was being uploaded to the server in the process of project creation.  The exception on the server was:

16:42:38 [XNIO-2 task-26] ERROR - UT000128: Remote peer closed connection before all data could be read
java.io.IOException: UT000128: Remote peer closed connection before all data could be read
        at io.undertow.conduits.FixedLengthStreamSourceConduit.exitRead(FixedLengthStreamSourceConduit.java:338) ~[undertow-core.jar:1.3.4.Final]
        at io.undertow.conduits.FixedLengthStreamSourceConduit.read(FixedLengthStreamSourceConduit.java:255) ~[undertow-core.jar:1.3.4.Final]
        at org.xnio.conduits.ConduitStreamSourceChannel.read(ConduitStreamSourceChannel.java:127) ~[xnio-api.jar:3.3.2.Final]
        at io.undertow.channels.DetachableStreamSourceChannel.read(DetachableStreamSourceChannel.java:209) ~[undertow-core.jar:1.3.4.Final]
        at io.undertow.server.HttpServerExchange$ReadDispatchChannel.read(HttpServerExchange.java:2211) ~[undertow-core.jar:1.3.4.Final]
        at org.xnio.channels.Channels.readBlocking(Channels.java:294) ~[xnio-api.jar:3.3.2.Final]
        at io.undertow.io.UndertowInputStream.readIntoBuffer(UndertowInputStream.java:109) ~[undertow-core.jar:1.3.4.Final]
        at io.undertow.io.UndertowInputStream.read(UndertowInputStream.java:89) ~[undertow-core.jar:1.3.4.Final]
        at java.io.ObjectInputStream$PeekInputStream.read(ObjectInputStream.java:2338) ~[na:1.8.0_112]
        at java.io.ObjectInputStream$BlockDataInputStream.refill(ObjectInputStream.java:2562) ~[na:1.8.0_112]
        at java.io.ObjectInputStream$BlockDataInputStream.read(ObjectInputStream.java:2730) ~[na:1.8.0_112]
        at java.io.ObjectInputStream.read(ObjectInputStream.java:868) ~[na:1.8.0_112]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_112]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265) ~[na:1.8.0_112]
        at java.io.DataInputStream.readInt(DataInputStream.java:389) ~[na:1.8.0_112]
        at org.semanticweb.binaryowl.lookup.IRILookupTable.readIndex(IRILookupTable.java:233) ~[org.protege.owl.server.jar:na]

**Comment by NCIEVS** [comment]
This was tested by EHD in the same laptop but from the office/LAN.  Project creation proceeded without issues and took about 2 minutes.  So no bug except that the timeout period is too short for work over VPN.

Feature request is to increase the timeout period (or do multipart?) so that the workflow managers can create projects remotely while on VPN.

**Comment by NCIEVS** [comment]
Timeout has been increased to 30 mins.  Testing needs to be done remotely, create a project with a full size NCIt over VPN.

**Comment by bdionne** [comment]
Itendra: How to create a Full size project in order for the time out to be tested ? Will a normal Project creation over VPN suffice for this requirement/issue ?If its an admin function, i think Dev can test it ?

You need to login using the admin port, `8081`, though your QA server might use a different port (see Tracy). The user you login as has to have permissions to create a project. You then create a new project using the file for the full thesaurus.

This needs to be done over the VPN. Originally this was reported by Liz

**Comment by singhik** [comment]
This is an Admin operation Test which needs to be performed by Admin roles, hence assigning it to Tracy Safran @safrant  ...

**Comment by NCIEVS** [comment]
Oh, you should have admin role in the QA environment.  @safrant should add you as an admin.

**Comment by bdionne** [comment]
@singhik - yea this is not the usual `sysadmin` kind of thing. We have a notion of `workflow manager` who is responsible for maintaining the projects, configuring properties in the projects, assigning user permissions and so forth.

Most of this functionality is accessed using the `Admin` plugin which requires logging in on port `8081` as a manager

**Comment by safrant** [comment]
I was able to create a new project remotely.  It took about 20 minutes.
