### ISSUE TITLE
Null pointer in retirement

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#18]
```
java.lang.NullPointerException: null
        at gov.nih.nci.ui.NCIEditTab.addNotes(NCIEditTab.java:484) ~[na:na]
        at gov.nih.nci.ui.NCIEditTab.completeRetire(NCIEditTab.java:500) ~[na:na
]
        at gov.nih.nci.ui.RetirePanel$1.actionPerformed(RetirePanel.java:154) ~[
na:na]
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) ~[na:1
.8.0_91]
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) ~[
na:1.8.0_91]
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) ~[
na:1.8.0_91]
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source) ~[na:1.8.0_
91]
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Sour
ce) ~[na:1.8.0_91]
        at java.awt.Component.processMouseEvent(Unknown Source) ~[na:1.8.0_91]
        at javax.swing.JComponent.processMouseEvent(Unknown Source) ~[na:1.8.0_9
1]
        at java.awt.Component.processEvent(Unknown Source) ~[na:1.8.0_91]
        at java.awt.Container.processEvent(Unknown Source) ~[na:1.8.0_91]
        at java.awt.Component.dispatchEventImpl(Unknown Source) ~[na:1.8.0_91]
        at java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:1.8.0_91]
        at java.awt.Component.dispatchEvent(Unknown Source) ~[na:1.8.0_91]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) ~[n
a:1.8.0_91]
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) ~[na
:1.8.0_91]
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) ~[na:1.8
.0_91]
        at java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:1.8.0_91]
        at java.awt.Window.dispatchEventImpl(Unknown Source) ~[na:1.8.0_91]
        at java.awt.Component.dispatchEvent(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventQueue.access$500(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventQueue$3.run(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventQueue$3.run(Unknown Source) ~[na:1.8.0_91]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0
_91]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(Unknown Source) ~[na:1.8.0_91]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventQueue$4.run(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventQueue$4.run(Unknown Source) ~[na:1.8.0_91]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0
_91]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [
na:1.8.0_91]
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [na:
1.8.0_91]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [
na:1.8.0_91]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_91]

        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_91]

        at java.awt.EventDispatchThread.run(Unknown Source) [na:1.8.0_91]
```

**Comment by NCIEVS** [comment]
@bdionne, this seems to have been fixed.  Can i set to bug, fixed, ready for QA?

**Comment by bdionne** [comment]
Things have changed a lot since I opened this, mostly as a placeholder. I'm not sure there's much to test here other than to watch for this occurring again

**Comment by NCIEVS** [comment]
Ok, I'll clear all the labels and set it for investigation & future release.

**Comment by bdionne** [comment]
this code has moved elsewhere, let's reopen if it shows up again
