### ISSUE TITLE
Revision diff panel fails to commit rejections

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#191]
The subject is: http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#RAS_Family_Oncogene
An error was thrown: Server in maintenance mode, please try later
org.protege.editor.owl.client.api.exception.ClientRequestException: Server in maintenance mode, please try later
        at org.protege.editor.owl.client.LocalHttpClient.throwRequestExceptions(LocalHttpClient.java:716) ~[protege-client-3.0.0-SNAPSHOT.jar:na]
        at org.protege.editor.owl.client.LocalHttpClient.post(LocalHttpClient.java:557) ~[protege-client-3.0.0-SNAPSHOT.jar:na]
        at org.protege.editor.owl.client.LocalHttpClient.commit(LocalHttpClient.java:249) ~[protege-client-3.0.0-SNAPSHOT.jar:na]
        at org.protege.editor.owl.client.diff.ui.ReviewButtonsPanel.commit(ReviewButtonsPanel.java:248) [protege-client-3.0.0-SNAPSHOT.jar:na]
        at org.protege.editor.owl.client.diff.ui.ReviewButtonsPanel.lambda$new$0(ReviewButtonsPanel.java:228) [protege-client-3.0.0-SNAPSHOT.jar:na]
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source) ~[na:1.8.0_102]
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.processMouseEvent(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.JComponent.processMouseEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.processEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Container.processEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.dispatchEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Window.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.dispatchEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventQueue.access$500(Unknown Source) ~[na:1.8.0_102]
 
 
 
while rejecting a class edit & committing, it took a long time to refresh the gui.  not certain whether all the changesets in memory affected the performance in here or we have a bug, a potential location is the Save as we got warned that the class was being edited.  The server was paused, changes while in the revision history panel needed the "pause server" to be unchecked (before this wasn't the case)
 
 
Checking for updates
The subject is: http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#Actinobaculum_schaalii
An error was thrown: Server in maintenance mode, please try later
org.protege.editor.owl.client.api.exception.ClientRequestException: Server in maintenance mode, please try later
        at org.protege.editor.owl.client.LocalHttpClient.throwRequestExceptions(LocalHttpClient.java:716) ~[protege-client-3.0.0-SNAPSHOT.jar:na]
        at org.protege.editor.owl.client.LocalHttpClient.post(LocalHttpClient.java:557) ~[protege-client-3.0.0-SNAPSHOT.jar:na]
        at org.protege.editor.owl.client.LocalHttpClient.commit(LocalHttpClient.java:249) ~[protege-client-3.0.0-SNAPSHOT.jar:na]
        at org.protege.editor.owl.client.diff.ui.ReviewButtonsPanel.commit(ReviewButtonsPanel.java:248) [protege-client-3.0.0-SNAPSHOT.jar:na]
        at org.protege.editor.owl.client.diff.ui.ReviewButtonsPanel.lambda$new$0(ReviewButtonsPanel.java:228) [protege-client-3.0.0-SNAPSHOT.jar:na]
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source) ~[na:1.8.0_102]
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.processMouseEvent(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.JComponent.processMouseEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.processEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Container.processEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.dispatchEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]
 
 
while saving history from the revision history panel, got an exception and couldn't save history
Server failed to generate concept history (contact server admin for further assistance)
org.protege.editor.owl.client.api.exception.ClientRequestException: Server failed to generate concept history (contact server admin for further assistance)
        at org.protege.editor.owl.client.LocalHttpClient.throwRequestExceptions(LocalHttpClient.java:720) ~[protege-client-3.0.0-SNAPSHOT.jar:na]
        at org.protege.editor.owl.client.LocalHttpClient.get(LocalHttpClient.java:603) ~[protege-client-3.0.0-SNAPSHOT.jar:na]
        at org.protege.editor.owl.client.LocalHttpClient.genConceptHistory(LocalHttpClient.java:681) ~[protege-client-3.0.0-SNAPSHOT.jar:na]
        at org.protege.editor.owl.client.diff.ui.ReviewButtonsPanel$6.actionPerformed(ReviewButtonsPanel.java:174) [protege-client-3.0.0-SNAPSHOT.jar:na]
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) [na:1.8.0_102]
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) [na:1.8.0_102]
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) [na:1.8.0_102]
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source) [na:1.8.0_102]
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source) [na:1.8.0_102]
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source) [na:1.8.0_102]
 
committing prompt accept/rejects resulted in another "server is in maintenance mode"
 
 
 
 
 
fresh launch of protege, continuing with baseline workflow, after having had some commit & history writing issues in a previous session, screenshot further below shows 'bad widget conflicts panel'
 
 
An error occurred whilst creating the view content for the 'Conflicts (list)' view: {}
java.lang.NullPointerException: null
        at org.protege.editor.owl.client.diff.ui.ConflictsListPanel.createConflictsPanel(ConflictsListPanel.java:131) ~[na:na]
        at org.protege.editor.owl.client.diff.ui.ConflictsListPanel.createSubPanel(ConflictsListPanel.java:119) ~[na:na]
        at org.protege.editor.owl.client.diff.ui.ConflictsListPanel.getConflictsScrollPane(ConflictsListPanel.java:94) ~[na:na]
        at org.protege.editor.owl.client.diff.ui.ConflictsListPanel.addConflictDetails(ConflictsListPanel.java:84) ~[na:na]
        at org.protege.editor.owl.client.diff.ui.ConflictsListPanel.<init>(ConflictsListPanel.java:47) ~[na:na]
        at org.protege.editor.owl.client.diff.ui.ConflictsListView.initialiseOWLView(ConflictsListView.java:18) ~[na:na]
        at org.protege.editor.owl.ui.view.AbstractOWLViewComponent.initialise(AbstractOWLViewComponent.java:43) ~[na:na]
        at org.protege.editor.core.ui.view.View.createContent(View.java:422) [protege-editor-core.jar:na]
        at org.protege.editor.core.ui.view.View.createUI(View.java:229) [protege-editor-core.jar:na]
        at org.protege.editor.core.ui.view.View$1.hierarchyChanged(View.java:130) [protege-editor-core.jar:na]
        at java.awt.Component.processHierarchyEvent(Unknown Source) [na:1.8.0_102]
        at java.awt.Component.processEvent(Unknown Source) [na:1.8.0_102]
        at java.awt.Container.processEvent(Unknown Source) [na:1.8.0_102]
        at java.awt.Component.dispatchEventImpl(Unknown Source) [na:1.8.0_102]
        at java.awt.Container.dispatchEventImpl(Unknown Source) [na:1.8.0_102]
        at java.awt.Component.dispatchEvent(Unknown Source) [na:1.8.0_102]
        at java.awt.Component.createHierarchyEvents(Unknown Source) [na:1.8.0_102]
        at java.awt.Container.createHierarchyEvents(Unknown Source) [na:1.8.0_102]
        at java.awt.Container.createHierarchyEvents(Unknown Source) [na:1.8.0_102]
        at java.awt.Container.createHierarchyEvents(Unknown Source) [na:1.8.0_102]
 
 
 
                update master server config after squashing and generating a new baseline
 
 
restarted, as usual, this time revision history came up fine.  But doing a test reject and a commit resulted in an exception, below, and the uncommitted changes showed up in the server menu.  the commit submenu is now disabled and the commit cannot be done.
 
BADLY BEHAVING LISTENER: null has been removed
java.lang.NullPointerException: null
        at gov.nih.nci.ui.NCIEditTab.refreshNavTree(NCIEditTab.java:156) ~[na:na]
        at gov.nih.nci.ui.NCIEditTab.setCurrentlyEditing(NCIEditTab.java:203) ~[na:na]
        at gov.nih.nci.ui.NCIEditTab.stateChanged(NCIEditTab.java:1221) ~[na:na]
        at org.protege.editor.owl.client.SessionRecorder.fireStateChanged(SessionRecorder.java:231) ~[na:na]
        at org.protege.editor.owl.client.SessionRecorder.logChanges(SessionRecorder.java:164) ~[na:na]
        at org.protege.editor.owl.model.OWLModelManagerImpl.ontologiesChanged(OWLModelManagerImpl.java:705) [protege-editor-owl.jar:na]
        at org.semanticweb.owlapi.model.DefaultChangeBroadcastStrategy.broadcastChanges(DefaultChangeBroadcastStrategy.java:38) ~[owlapi-osgidistribution.jar:4.
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.broadcastChanges(OWLOntologyManagerImpl.java:1528) [owlapi-osgidistribution.jar:4.2.6.20160910-
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.applyChanges(OWLOntologyManagerImpl.java:612) [owlapi-osgidistribution.jar:4.2.6.20160910-2108]
        at org.protege.editor.owl.model.OWLModelManagerImpl.applyChanges(OWLModelManagerImpl.java:694) [protege-editor-owl.jar:na]
        at org.protege.editor.owl.client.diff.model.LogDiffManager.applyOntologyChanges(LogDiffManager.java:213) [protege-client-3.0.0-SNAPSHOT.jar:na]
        at org.protege.editor.owl.client.diff.ui.ReviewButtonsPanel.commit(ReviewButtonsPanel.java:245) [protege-client-3.0.0-SNAPSHOT.jar:na]
        at org.protege.editor.owl.client.diff.ui.ReviewButtonsPanel.lambda$new$0(ReviewButtonsPanel.java:228) [protege-client-3.0.0-SNAPSHOT.jar:na]
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) ~[na:1.8.0_102]
 
proceeding from above, the save to concept history failed with another exception, below
 
Server failed to generate concept history (contact server admin for further assistance)
org.protege.editor.owl.client.api.exception.ClientRequestException: Server failed to generate concept history (contact server admin for further assistance)
        at org.protege.editor.owl.client.LocalHttpClient.throwRequestExceptions(LocalHttpClient.java:720) ~[protege-client-3.0.0-SNAPSHOT.jar:na]
        at org.protege.editor.owl.client.LocalHttpClient.get(LocalHttpClient.java:603) ~[protege-client-3.0.0-SNAPSHOT.jar:na]
        at org.protege.editor.owl.client.LocalHttpClient.genConceptHistory(LocalHttpClient.java:681) ~[protege-client-3.0.0-SNAPSHOT.jar:na]
        at org.protege.editor.owl.client.diff.ui.ReviewButtonsPanel$6.actionPerformed(ReviewButtonsPanel.java:174) [protege-client-3.0.0-SNAPSHOT.jar:na]
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) [na:1.8.0_102]
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) [na:1.8.0_102]
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) [na:1.8.0_102]
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source) [na:1.8.0_102]
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source) [na:1.8.0_102]
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source) [na:1.8.0_102]
        at java.awt.Component.processMouseEvent(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.processMouseEvent(Unknown Source) [na:1.8.0_102]
        at java.awt.Component.processEvent(Unknown Source) [na:1.8.0_102]
        at java.awt.Container.processEvent(Unknown Source) [na:1.8.0_102]
        at java.awt.Component.dispatchEventImpl(Unknown Source) [na:1.8.0_102]
        at java.awt.Container.dispatchEventImpl(Unknown Source) [na:1.8.0_102]
        at java.awt.Component.dispatchEvent(Unknown Source) [na:1.8.0_102]
 
After modifying the date & version history in the "active ontology" panel, the changes could not be committed as the commit button was still disabled, Probably related to the "badly behaving listener" exception above.
 
image001.png

**Comment by bdionne** [comment]
![image001](https://cloud.githubusercontent.com/assets/31741/22846720/dd83e566-efb6-11e6-8db9-5319efb00be7.png)

**Comment by bdionne** [comment]
relates to #228

**Comment by rmehri** [comment]
Hi this fix has been retested and verified using tag nci-1.0068.
Used Local server: 8080, Workflow-Manager
Please see attached snapshot for more detail.

![issue-191](https://user-images.githubusercontent.com/8367102/27191403-b067cd24-51c5-11e7-9bbc-b6fc2ae7afbb.png)

Thanks,
Reza

**Comment by rmehri** [comment]
Hi this fix has been retested and verified using tag nci-1.0069. the same errors did not occur when I committed  a rejection.  Used Local server: 8080,  Workflow-Manager. Please see attached snapshot for more detail.
![commit1](https://user-images.githubusercontent.com/8367102/27302898-e21bd1fa-5506-11e7-879a-cbb6c17fbac8.png)
![commit2](https://user-images.githubusercontent.com/8367102/27302897-e21b183c-5506-11e7-9adf-185512c3e7c6.png)
![commit3](https://user-images.githubusercontent.com/8367102/27302900-e21eba8c-5506-11e7-9352-9970bc2cf5bf.png)
![commit4](https://user-images.githubusercontent.com/8367102/27302899-e21e1e06-5506-11e7-85e4-5ecb7d82dabe.png)

Thanks,
Reza

**Comment by rmehri** [comment]
Hi, 
I  have caught this error while retesting this issue https://github.com/NCIEVS/nci-protege5/issues/292
Possibly, this is intermittent problem. 

Steps to reproduce:
1.	Launch server and client
2.	Launch two separate client sessions and log into each one as (Workflow-Editor and Workflow-Manager)
3.	Do pre-merge of two concepts using Workflow-Editor login
4.	Do merge to complete the pre-merge using Workflow-Manager login
5.	Go back to client page that has workflow- editor login and double check on retired folder to see if the merged class exists.
6.	Go to client page that has Workflow-Manager and select Revision History page and do the following:
a.	Refresh the page to see the merged class (I did not see latest up on merged concept
b.	Remove the revision history tab then re-selected revision history tab from Window/tab then you’ll see the errors.
Please see attached screenshot for more details. 

![revision history tab](https://user-images.githubusercontent.com/8367102/27305836-5b5dda68-5511-11e7-8e49-f23578dc2d94.png)

Thanks,
Reza

**Comment by bdionne** [comment]
@rmehri - this is really a separate issue, which I've opened a new [ticket](https://github.com/NCIEVS/nci-protege5/issues/304) for

**Comment by rmehri** [comment]
Ok sure and thanks
Reza
