### ISSUE TITLE
NCI Edit Tab-Split By Right Click on A Class Causes Exception If Property Rows Selected 

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#196]
The split of a class by right click on it, it works fine. But if one or more of a class property rows selected then right click on the class and pressing the Split causes exception error.   

Used the following:
 Servers: http://localhost:8080 & https://nciws-d699-v.nci.nih.gov:9090
 Logins: Modeler & Manager

Tag-120 & NCI Edit-0.4.2

Steps to reproduce:
 1.Launch protégé server and client
 2.Log into the local server (8080), login: modeler
 3.Select NCI Edit Tab
 4.Select a class (Concept)
 5.Select  one or more property rows then,
 6. Right click on the class then select Split, which causes the errors below:
2017-02-15 13:40:17.488 [AWT-EventQueue-0] ERROR ProtegeApplication    Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.NullPointerException: null
	at gov.nih.nci.ui.action.SplitClassAction.actionPerformed(SplitClassAction.java:29) ~[na:na]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) ~[na:1.8.0_101]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) ~[na:1.8.0_101]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) ~[na:1.8.0_101]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) ~[na:1.8.0_101]
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376) ~[na:1.8.0_101]
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833) ~[na:1.8.0_101]
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877) ~[na:1.8.0_101]
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289) ~[na:1.8.0_101]
	at java.awt.Component.processMouseEvent(Component.java:6533) ~[na:1.8.0_101]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[na:1.8.0_101]
	at java.awt.Component.processEvent(Component.java:6298) ~[na:1.8.0_101]
	at java.awt.Container.processEvent(Container.java:2236) ~[na:1.8.0_101]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[na:1.8.0_101]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[na:1.8.0_101]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[na:1.8.0_101]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) ~[na:1.8.0_101]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) ~[na:1.8.0_101]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) ~[na:1.8.0_101]
	at java.awt.Container.dispatchEventImpl(Container.java:2280) ~[na:1.8.0_101]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[na:1.8.0_101]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[na:1.8.0_101]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[na:1.8.0_101]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_101]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[na:1.8.0_101]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[na:1.8.0_101]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_101]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) ~[na:1.8.0_101]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[na:1.8.0_101]
	at java.awt.EventQueue$4.run(EventQueue.java:731) ~[na:1.8.0_101]
	at java.awt.EventQueue$4.run(EventQueue.java:729) ~[na:1.8.0_101]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_101]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) ~[na:1.8.0_101]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[na:1.8.0_101]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_101]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_101]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_101]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_101]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_101]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_101]

Please see attached zip file to play the video and log file for more details. 

[protege_Console_Log.zip](https://github.com/NCIEVS/nci-protege5/files/778156/protege_Console_Log.zip)

Thanks,
Reza

**Comment by rmehri** [comment]
Hi 
*The same error happens for Cloning and Merging of a class via right click on it.

Thanks,
Reza

**Comment by bdionne** [comment]
The exception is harmless, I'll add some code to catch and swallow it. The issue is when you click away from the tree view, the focus is lost. The control that manages the popups doesn't know this when you right click again. So a popup menu is displayed that is not accurate, selecting an item like split causes it to fail.

This is the same issue you see where sometimes the actions in the popup are greyed out. The simple workaround is to just click left on the class again and the popup will correctly display and behave.

**Comment by rmehri** [comment]
Hi Bob, 
Thanks for your feedback! I will retest this issue in next release. 
Reza

**Comment by bdionne** [comment]
You're welcome @rmehri - I think the issues to focus testing on now are the 10 remaining in the `In QA` bucket. We need to finish those before we can freeze the code and start the UAT.

**Comment by rmehri** [comment]
Sure and I'll do that. 
 Thanks,
 Reza

**Comment by bdionne** [comment]
[exception should be gone](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.4.4)

**Comment by rmehri** [comment]
Based on status of this issue and development feedback, I have retested this issue using tag-121, nci edit tab-0.4.4.  I selected one or more property rows and used right click on the class, and it did not allow me to do split. No errors were occurred. 

Thanks,
Reza
