### ISSUE TITLE
canceling out of an annotation property

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#205]
Exception thrown when canceling out of an annotation property.  Haven't been able to reproduce it, and can't say that it interferes with subsequent editing.  Just note it and keep it for a while as "watch-and-wait".

Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.NullPointerException: null
        at org.protege.editor.owl.ui.view.annotationproperty.OWLAnnotationPropertyHierarchyViewComponent.createNewChild(OWLAnnotationPropertyHierarchyViewComponent.java:100) ~[na:na]
        at org.protege.editor.owl.ui.view.annotationproperty.OWLAnnotationPropertyHierarchyViewComponent$1.actionPerformed(OWLAnnotationPropertyHierarchyViewComponent.java:48) ~[na:na]
        at org.protege.editor.core.ui.view.ViewActionAdapter.actionPerformed(ViewActionAdapter.java:48) ~[na:na]
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source) ~[na:1.8.0_102]
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source) ~[na:1.8.0_102]

**Comment by bdionne** [comment]
This is easy to see looking at the code. If you create a child it fails every time when you cancel out, but when you create a sibling it works. Anyway, these null pointers are usually easy to [fix](https://github.com/bdionne/protege/commit/ce3fde65e84799) looking at the source

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.124)

**Comment by rmehri** [comment]
Hi, 
This fix has been retested and verified in tag 124, nci edit -0.4.8. Please see attached screen shots for more detail. 

![cancel_annotation properties](https://cloud.githubusercontent.com/assets/8367102/23775499/fc4c5bae-04f6-11e7-8ae1-14363fe574b1.png)
![cancel_annotation properties-1](https://cloud.githubusercontent.com/assets/8367102/23775503/fec87a48-04f6-11e7-895c-b8325c447e58.png)
Thanks,
Reza
