### ISSUE TITLE
protege server doesn't always exit gracefully

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#233]
the admin and vocab server terminate, but undertow doesn't always.  here's an exception.

16:56:11 [XNIO-2 task-6] INFO  - Stopping server instances
16:56:11 [XNIO-2 task-6] INFO  - ... Web server has stopped
16:56:11 [XNIO-2 task-6] INFO  - ... Admin server has stopped
16:56:11 [XNIO-2 task-6] ERROR - UT005071: Undertow request failed HttpServerExchange{ POST /nci_protege/server/shutdown request {Accept=[*/*], Authorization=[Basic ZnJhZ29zb2dBZG1pbjo1OTBiMDEzZi1lYjQyLTRmOTctYTlkMi1mMDk2M2U0M2ZhODM=], User-Agent=[curl/7.29.0], Host=[nciws-d699-v.nci.nih.gov:9091]} response {Content-Length=[0]}}
java.util.concurrent.RejectedExecutionException: XNIO007007: Thread is terminating
        at org.xnio.nio.WorkerThread.executeAfter(WorkerThread.java:595) ~[xnio-nio.jar:3.3.2.Final]
        at io.undertow.util.DateUtils.addDateHeaderIfRequired(DateUtils.java:247) ~[undertow-core.jar:1.3.4.Final]
        at io.undertow.server.protocol.http.HttpTransferEncoding.createSinkConduit(HttpTransferEncoding.java:203) ~[undertow-core.jar:1.3.4.Final]
        at io.undertow.server.protocol.http.HttpServerConnection.getSinkConduit(HttpServerConnection.java:205) ~[undertow-core.jar:1.3.4.Final]
        at io.undertow.server.HttpServerExchange.getResponseChannel(HttpServerExchange.java:1244) ~[undertow-core.jar:1.3.4.Final]
        at io.undertow.io.UndertowOutputStream.close(UndertowOutputStream.java:337) ~[undertow-core.jar:1.3.4.Final]
        at io.undertow.server.HttpServerExchange$DefaultBlockingHttpExchange.close(HttpServerExchange.java:1825) ~[undertow-core.jar:1.3.4.Final]
        at io.undertow.server.HttpServerExchange.endExchange(HttpServerExchange.java:1544) ~[undertow-core.jar:1.3.4.Final]
        at org.protege.editor.owl.server.http.handlers.HTTPServerHandler.handleRequest(HTTPServerHandler.java:29) ~[org.protege.owl.server.jar:na]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:198) ~[undertow-core.jar:1.3.4.Final]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:788) ~[undertow-core.jar:1.3.4.Final]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]

**Comment by bdionne** [comment]
I see the issue here. The web listener is shutdown in the `POST` request, so the call to end exchange sometimes crashes, though it shouldn't if the graceful shutdown handler is doing it's thing.

I think we can move the call to shutdown the listener to after the end exchange occurs and that should clear it up

**Comment by bdionne** [comment]
I suspect this [patch](https://github.com/bdionne/protege-server/commit/52f3cfbf2ad877f1d5b2bd4c3285151a631eb62b?diff=unified) will resolve the issue.

If I put a small sleep in before the end exchange call I can create the exception above every time. Moving the call to stop the listener until after the exchange ends seems to fix it.

**Comment by bdionne** [comment]
This is a sysadmin issue, the web servers shutdown but the JVM does not exit. 

This is tested by running the shutdown script, and like the deadlocks just something to watch

**Comment by rmehri** [comment]
Hi,

I retested this issue using latest tag nci-1.004. 
Steps to reproduce:

1) Launched protégé server and client on local server.
2) Uses Git Bash session and located the shut down script and ran it and the command did not get recognized and received the errors below:    Please see attached screenshot for more detail and let me know your thoughts and/or the reproducible steps
Please let me know if your steps to verify this fix 

"$ ./shutdown.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0./shutdown.sh: line 7: jq: command not found
curl: (7) Failed to connect to localhost port 80: Connection refused
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0./shutdown.sh: line 20: jq: command not found
curl: (7) Failed to connect to localhost port 80: Connection refused
"

![issue-233-shutdown](https://cloud.githubusercontent.com/assets/8367102/25354567/5ceec7fc-2901-11e7-8453-11fd7ba0896d.png)

Thanks,
Reza

**Comment by bdionne** [comment]
`jq` is a utility that is in the server directory. If it's not installed on your machine then you need to modify the `shutdown.sh` script to reference `./jq`

Note that the [script](https://github.com/bdionne/protege-server/blob/master/scripts/shutdown.sh#L2-L4) takes three arguments, the port, .eg. `8081` or whatever port you run admin on, the sysadmin user, .eg. `root` and the sysadmin password.

**Comment by rmehri** [comment]
Thanks for the feedback! I have retested and verified this issue using nci-1.006. Please see attached screenshot for more detail.

![issue-233](https://cloud.githubusercontent.com/assets/8367102/25972158/d790acb4-366c-11e7-9f5b-c5b4a9478b8d.png)
Thanks,
Reza
