### ISSUE TITLE
Dragging Protege Browser to Minimize the Screen Causes Exception Error

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#247]
Used:
Servers: http://localhost:8080 & https://nciws-d699-v.nci.nih.gov:9090
Logins: Modeler & Manager
Tag-126 & NCI Edit-0.5.1
Steps to reproduce:
1.	Launch protégé server and client
2.	Log into the local server (8080)
3.	Drag right top navigator of browser and drag it toward down and try to minimize the browser and you will notice the exception errors.  
*Note: this behavior occurs with and without login to the  protgege.
Please see attached screen shots and console log file for more details. 

![drag to minimize_error-1](https://cloud.githubusercontent.com/assets/8367102/24379112/95e21aea-1313-11e7-9135-f711f26fa1a2.png)
![drag to minimize_error-2](https://cloud.githubusercontent.com/assets/8367102/24379114/97df8698-1313-11e7-9bae-f159591f5be3.png)
![drag to minimize_error-3](https://cloud.githubusercontent.com/assets/8367102/24379119/9c257c3a-1313-11e7-9ccb-4d39b2ca08a2.png)

![drag to minimize_error-4](https://cloud.githubusercontent.com/assets/8367102/24379123/a21c5c9e-1313-11e7-9fe9-35fcf591f994.png)

[protege_Logfile.txt](https://github.com/NCIEVS/nci-protege5/files/873883/protege_Logfile.txt)

2017-03-27 17:21:13.582 [AWT-EventQueue-0] ERROR ProtegeApplication    Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.IllegalArgumentException: Width and height must be >= 0
	at javax.swing.plaf.basic.BasicHTML.getHTMLBaseline(BasicHTML.java:86) ~[na:1.8.0_101]
	at javax.swing.plaf.basic.BasicHTML.getBaseline(BasicHTML.java:104) ~[na:1.8.0_101]
	at javax.swing.plaf.basic.BasicLabelUI.getBaseline(BasicLabelUI.java:293) ~[na:1.8.0_101]
	at javax.swing.JComponent.getBaseline(JComponent.java:2564) ~[na:1.8.0_101]
	at javax.swing.plaf.basic.BasicComboBoxUI.getBaseline(BasicComboBoxUI.java:999) ~[na:1.8.0_101]
	at javax.swing.JComponent.getBaseline(JComponent.java:2564) ~[na:1.8.0_101]
	at java.awt.GridBagLayout.alignOnBaseline(GridBagLayout.java:1829) ~[na:1.8.0_101]
	at java.awt.GridBagLayout.AdjustForGravity(GridBagLayout.java:1656) ~[na:1.8.0_101]
	at java.awt.GridBagLayout.adjustForGravity(GridBagLayout.java:1610) ~[na:1.8.0_101]
	at java.awt.GridBagLayout.ArrangeGrid(GridBagLayout.java:2200) ~[na:1.8.0_101]
	at java.awt.GridBagLayout.arrangeGrid(GridBagLayout.java:2031) ~[na:1.8.0_101]
	at java.awt.GridBagLayout.layoutContainer(GridBagLayout.java:812) ~[na:1.8.0_101]
	at java.awt.Container.layout(Container.java:1510) ~[na:1.8.0_101]
	at java.awt.Container.doLayout(Container.java:1499) ~[na:1.8.0_101]
	at java.awt.Container.validateTree(Container.java:1695) ~[na:1.8.0_101]
	at java.awt.Container.validateTree(Container.java:1704) ~[na:1.8.0_101]
	at java.awt.Container.validateTree(Container.java:1704) ~[na:1.8.0_101]
	at java.awt.Container.validateTree(Container.java:1704) ~[na:1.8.0_101]
	at java.awt.Container.validateTree(Container.java:1704) ~[na:1.8.0_101]
	at java.awt.Container.validateTree(Container.java:1704) ~[na:1.8.0_101]
	at java.awt.Container.validate(Container.java:1630) ~[na:1.8.0_101]
	at sun.awt.windows.WComponentPeer$1.run(WComponentPeer.java:198) ~[na:1.8.0_101]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[na:1.8.0_101]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756) ~[na:1.8.0_101]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_101]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[na:1.8.0_101]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[na:1.8.0_101]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_101]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) ~[na:1.8.0_101]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[na:1.8.0_101]
	at java.awt.EventQueue$4.run(EventQueue.java:731) ~[na:1.8.0_101]
	at java.awt.EventQueue$4.run(EventQueue.java:729) ~[na:1.8.0_101]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_101]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) ~[na:1.8.0_101]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[na:1.8.0_101]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_101]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_101]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_101]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_101]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_101]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_101]

Thanks,
Reza

**Comment by bdionne** [comment]
Thanks Reza,

I see the same behavior if I scrunch the app down enough, but all I see is an exception, if I resize it back everything seems to still work.

Is there something specific that doesn't work?

**Comment by rmehri** [comment]
Hi Bob, 
You're welcome! No, it actually stays logged on and the classes' contents are stable and accessible.  
Thanks,
Reza

**Comment by bdionne** [comment]
no real issue here
