### ISSUE TITLE
Deadlock related to equivalent class navigation

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#250]
From [EHD]
"I had another lock, this time I was trying to add a parent to a concept but then I got a popup saying the concept was already being edited and it asked if I wanted to continue. I hit yes, but maybe it thought I was editing the last concept I touched.  (I was adding a parent to POLR2L Gene C114340, the last concept I had touched was DNA-Directed RNA Polymerases I, II, and III Subunit RPABC5 C114343. I had tried to hit the link in the restriction Gene_Product_Encoded_By_Gene some POLR2L Gene to get to C114340. The link didn’t work because C114343 is a defined concept.)"

Thread dump below.

"TimerQueue" #23 daemon prio=5 os_prio=0 tid=0x0000000033d6d800 nid=0x1fa4 waiting on condition [0x000000003866f000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000064a4766e0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
        at java.util.concurrent.DelayQueue.take(Unknown Source)
        at javax.swing.TimerQueue.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

"DestroyJavaVM" #20 prio=5 os_prio=0 tid=0x0000000033d6c000 nid=0xfd4 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"OSGi Shutdown Thread" #19 prio=5 os_prio=0 tid=0x0000000033d6b800 nid=0x23e4 in Object.wait() [0x0000000035bcf000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000006495ad280> (a org.apache.felix.framework.util.ThreadGate)
        at org.apache.felix.framework.util.ThreadGate.await(ThreadGate.java:79)
        - locked <0x00000006495ad280> (a org.apache.felix.framework.util.ThreadGate)
        at org.apache.felix.framework.Felix.waitForStop(Felix.java:1006)
        at org.protege.osgi.framework.Launcher.lambda$addCleanupOnExit$1(Launcher.java:148)
        at org.protege.osgi.framework.Launcher$$Lambda$28/195615004.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

"AWT-EventQueue-0" #16 prio=6 os_prio=0 tid=0x000000002baf3800 nid=0x978 waiting on condition [0x0000000032bcc000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000006496cc260> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(Unknown Source)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(Unknown Source)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(Unknown Source)
        at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(Unknown Source)
        at uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl.getEquivalentClassesAxioms(ConcurrentOWLOntologyImpl.java:1655)
        at org.semanticweb.owlapi.search.EntitySearcher.getEquivalentClasses(EntitySearcher.java:1015)
        at org.protege.editor.owl.model.hierarchy.AssertedClassHierarchyProvider.getEquivalents(AssertedClassHierarchyProvider.java:321)
        at org.protege.editor.owl.model.hierarchy.AssertedClassHierarchyProvider.getEquivalents(AssertedClassHierarchyProvider.java:23)
        at org.protege.editor.owl.ui.tree.OWLObjectTreeNode.getEquivalentObjects(OWLObjectTreeNode.java:44)
        at org.protege.editor.owl.ui.tree.OWLObjectTreeCellRenderer.getTreeCellRendererComponent(OWLObjectTreeCellRenderer.java:35)
        at javax.swing.plaf.basic.BasicTreeUI.paintRow(Unknown Source)
        at javax.swing.plaf.basic.BasicTreeUI.paint(Unknown Source)
        at javax.swing.plaf.ComponentUI.update(Unknown Source)
        at javax.swing.JComponent.paintComponent(Unknown Source)
        at org.protege.editor.owl.ui.tree.OWLObjectTree.paintComponent(OWLObjectTree.java:765)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        - locked <0x00000006495b7bc0> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JViewport.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        - locked <0x00000006495b7bc0> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintToOffscreen(Unknown Source)
        at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
        at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
        at javax.swing.RepaintManager.paint(Unknown Source)
        at javax.swing.JComponent._paintImmediately(Unknown Source)
        at javax.swing.JComponent.paintImmediately(Unknown Source)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.access$1200(Unknown Source)
        at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

"AWT-Windows" #14 daemon prio=6 os_prio=0 tid=0x000000002bfb1000 nid=0x219c runnable [0x000000002ff9f000]
   java.lang.Thread.State: RUNNABLE
        at sun.awt.windows.WToolkit.eventLoop(Native Method)
        at sun.awt.windows.WToolkit.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

"AWT-Shutdown" #13 prio=5 os_prio=0 tid=0x000000002bcbb000 nid=0x1a68 in Object.wait() [0x000000002ee2f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Unknown Source)
        at sun.awt.AWTAutoShutdown.run(Unknown Source)
        - locked <0x00000006495c7570> (a java.lang.Object)
        at java.lang.Thread.run(Unknown Source)

"Java2D Disposer" #12 daemon prio=10 os_prio=2 tid=0x000000002be2a000 nid=0x928 in Object.wait() [0x000000002dcbf000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.ref.ReferenceQueue.remove(Unknown Source)
        - locked <0x0000000649230ba0> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(Unknown Source)
        at sun.java2d.Disposer.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

"FelixStartLevel" #11 daemon prio=5 os_prio=0 tid=0x0000000028e31800 nid=0x1fc8 in Object.wait() [0x000000002b81e000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000006490c5b38> (a java.util.ArrayList)
        at java.lang.Object.wait(Unknown Source)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:279)
        - locked <0x00000006490c5b38> (a java.util.ArrayList)
        at java.lang.Thread.run(Unknown Source)

"FelixDispatchQueue" #10 prio=5 os_prio=0 tid=0x0000000028c53800 nid=0x20e8 in Object.wait() [0x000000002a4ee000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x0000000649021bf0> (a java.util.ArrayList)
        at java.lang.Object.wait(Unknown Source)
        at org.apache.felix.framework.util.EventDispatcher.run(EventDispatcher.java:1074)
        - locked <0x0000000649021bf0> (a java.util.ArrayList)
        at org.apache.felix.framework.util.EventDispatcher.access$000(EventDispatcher.java:55)
        at org.apache.felix.framework.util.EventDispatcher$1.run(EventDispatcher.java:102)
        at java.lang.Thread.run(Unknown Source)

"Service Thread" #9 daemon prio=9 os_prio=0 tid=0x00000000270f4000 nid=0x1fe4 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread2" #8 daemon prio=9 os_prio=2 tid=0x000000002707b800 nid=0x4a8 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #7 daemon prio=9 os_prio=2 tid=0x0000000027070800 nid=0xc94 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #6 daemon prio=9 os_prio=2 tid=0x00000000218eb000 nid=0x19b4 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Attach Listener" #5 daemon prio=5 os_prio=2 tid=0x00000000218e7800 nid=0x1a44 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=2 tid=0x00000000218e6800 nid=0x10d8 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=1 tid=0x00000000218ce000 nid=0x47c in Object.wait() [0x0000000024f2f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.ref.ReferenceQueue.remove(Unknown Source)
        - locked <0x000000064901a578> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(Unknown Source)
        at java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)

"Reference Handler" #2 daemon prio=10 os_prio=2 tid=0x0000000021887000 nid=0xd7c in Object.wait() [0x0000000023d3f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Unknown Source)
        at java.lang.ref.Reference.tryHandlePending(Unknown Source)
        - locked <0x0000000649012680> (a java.lang.ref.Reference$Lock)
        at java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)

"VM Thread" os_prio=2 tid=0x000000002187b800 nid=0x2200 runnable

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x000000000252c800 nid=0x2034 runnable

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x000000000252f000 nid=0xfa0 runnable

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x0000000002530800 nid=0x210c runnable

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x0000000002532800 nid=0x1468 runnable

"VM Periodic Task Thread" os_prio=2 tid=0x0000000027113800 nid=0x1b54 waiting on condition

JNI global references: 1993

Found one Java-level deadlock:
=============================
"Client-Server Communications":
  waiting to lock monitor 0x0000000035fad918 (object 0x00000006495b7bc0, a java.awt.Component$AWTTreeLock),
  which is held by "AWT-EventQueue-0"
"AWT-EventQueue-0":
  waiting for ownable synchronizer 0x00000006496cc260, (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync),
  which is held by "Client-Server Communications"

Java stack information for the threads listed above:
===================================================
"Client-Server Communications":
        at java.awt.Component.setFont(Unknown Source)
        - waiting to lock <0x00000006495b7bc0> (a java.awt.Component$AWTTreeLock)
        at java.awt.Container.setFont(Unknown Source)
        at javax.swing.JComponent.setFont(Unknown Source)
        at javax.swing.DefaultListCellRenderer.getListCellRendererComponent(Unknown Source)
        at org.protege.editor.core.ui.list.MList$MListCellRenderer.getListCellRendererComponent(MList.java:262)
        at org.protege.editor.owl.ui.framelist.OWLFrameList$OWLFrameListUI.updateLayoutState(OWLFrameList.java:916)
        at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(Unknown Source)
        at javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(Unknown Source)
        at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
        at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
        at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
        at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
        at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
        at javax.swing.DefaultListSelectionModel.removeSelectionIntervalImpl(Unknown Source)
        at javax.swing.DefaultListSelectionModel.clearSelection(Unknown Source)
        at javax.swing.JList.clearSelection(Unknown Source)
        at javax.swing.JList.setModel(Unknown Source)
        at javax.swing.JList.setListData(Unknown Source)
        at org.protege.editor.owl.ui.framelist.OWLFrameList.refillRows(OWLFrameList.java:394)
        at org.protege.editor.owl.ui.framelist.OWLFrameList.lambda$setupFrameListener$4(OWLFrameList.java:223)
        at org.protege.editor.owl.ui.framelist.OWLFrameList$$Lambda$136/1777363098.frameContentChanged(Unknown Source)
        at org.protege.editor.owl.ui.frame.AbstractOWLFrame.fireContentChanged(AbstractOWLFrame.java:113)
        at org.protege.editor.owl.ui.frame.AbstractOWLFrameSection.fireContentChanged(AbstractOWLFrameSection.java:328)
        at org.protege.editor.owl.ui.frame.AbstractOWLFrameSection.setRootObject(AbstractOWLFrameSection.java:283)
        at org.protege.editor.owl.ui.frame.AbstractOWLFrameSection.reset(AbstractOWLFrameSection.java:322)
        at org.protege.editor.owl.ui.frame.AbstractOWLFrameSection.processOntologyChanges(AbstractOWLFrameSection.java:93)
        at org.protege.editor.owl.ui.frame.AbstractOWLFrameSection.lambda$new$0(AbstractOWLFrameSection.java:54)
        at org.protege.editor.owl.ui.frame.AbstractOWLFrameSection$$Lambda$131/2135354546.ontologiesChanged(Unknown Source)
        at org.semanticweb.owlapi.model.DefaultChangeBroadcastStrategy.broadcastChanges(DefaultChangeBroadcastStrategy.java:38)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.broadcastChanges(OWLOntologyManagerImpl.java:1546)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.applyChanges(OWLOntologyManagerImpl.java:612)
        at org.protege.editor.owl.client.action.EnableAutoUpdateAction$AutoUpdate.performUpdate(EnableAutoUpdateAction.java:165)
        at org.protege.editor.owl.client.action.EnableAutoUpdateAction$AutoUpdate.run(EnableAutoUpdateAction.java:136)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
"AWT-EventQueue-0":
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000006496cc260> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(Unknown Source)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(Unknown Source)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(Unknown Source)
        at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(Unknown Source)
        at uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl.getEquivalentClassesAxioms(ConcurrentOWLOntologyImpl.java:1655)
        at org.semanticweb.owlapi.search.EntitySearcher.getEquivalentClasses(EntitySearcher.java:1015)
        at org.protege.editor.owl.model.hierarchy.AssertedClassHierarchyProvider.getEquivalents(AssertedClassHierarchyProvider.java:321)
        at org.protege.editor.owl.model.hierarchy.AssertedClassHierarchyProvider.getEquivalents(AssertedClassHierarchyProvider.java:23)
        at org.protege.editor.owl.ui.tree.OWLObjectTreeNode.getEquivalentObjects(OWLObjectTreeNode.java:44)
        at org.protege.editor.owl.ui.tree.OWLObjectTreeCellRenderer.getTreeCellRendererComponent(OWLObjectTreeCellRenderer.java:35)
        at javax.swing.plaf.basic.BasicTreeUI.paintRow(Unknown Source)
        at javax.swing.plaf.basic.BasicTreeUI.paint(Unknown Source)
        at javax.swing.plaf.ComponentUI.update(Unknown Source)
        at javax.swing.JComponent.paintComponent(Unknown Source)
        at org.protege.editor.owl.ui.tree.OWLObjectTree.paintComponent(OWLObjectTree.java:765)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        - locked <0x00000006495b7bc0> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JViewport.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        - locked <0x00000006495b7bc0> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintToOffscreen(Unknown Source)
        at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
        at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
        at javax.swing.RepaintManager.paint(Unknown Source)
        at javax.swing.JComponent._paintImmediately(Unknown Source)
        at javax.swing.JComponent.paintImmediately(Unknown Source)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.access$1200(Unknown Source)
        at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

Found 1 deadlock.

Heap
PSYoungGen      total 1581056K, used 632681K [0x0000000743000000, 0x00000007bda80000, 0x00000007c0000000)
  eden space 1210880K, 46% used [0x0000000743000000,0x00000007651a4178,0x000000078ce80000)
  from space 370176K, 19% used [0x00000007a7100000,0x00000007ab936518,0x00000007bda80000)
  to   space 399360K, 0% used [0x000000078ce80000,0x000000078ce80000,0x00000007a5480000)
ParOldGen       total 2918912K, used 707826K [0x0000000649000000, 0x00000006fb280000, 0x0000000743000000)
  object space 2918912K, 24% used [0x0000000649000000,0x000000067433c820,0x00000006fb280000)
Metaspace       used 54115K, capacity 56430K, committed 56576K, reserved 1097728K
  class space    used 7215K, capacity 7829K, committed 7936K, reserved 1048576K

**Comment by bdionne** [comment]
There is no specific test case that manifests this deadlock. It's just something to watch for

**Comment by rmehri** [comment]
Hi,
I have not experienced the reported errors during my testing.  As per your feedback, this ticket will remain open for the monitoring purpose.
Thanks,
Reza

**Comment by rmehri** [comment]
Hi, 
I have not seen the same error using my latest nci-1.006 on local server.  This ticket can be closed since there is a referenced open issue https://github.com/NCIEVS/nci-protege5/issues/271 

Thanks,
Reza
