### ISSUE TITLE
null pointer exception on local classification

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#267]
placeholder, can't say that this is related to a specific set of conditions, plus the classification was local rather than on the server: a) two null pointer exceptions were seen, and b) an independent classification within minutes of the first one resulted in a deadlock.  A third local classification went to completion.

NPEs in "a":

An error occurred during reasoning: null.
java.lang.NullPointerException: null
        at org.mindswap.pellet.KnowledgeBase.realize(KnowledgeBase.java:2147) ~[na:na]
        at com.clarkparsia.pellet.owlapiv3.PelletReasoner.precomputeInferences(PelletReasoner.java:1058) ~[na:na]
        at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.precompute(OWLReasonerManagerIm
pl.java:447) ~[na:na]
        at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.run(OWLReasonerManagerImpl.java
:388) ~[na:na]
        at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_102]
LOGBACK: No context given for org.protege.editor.core.log.LogManager$1[null]

and

An error occurred whilst filling the org.protege.editor.owl.ui.frame.cls.OWLEquivalentClassesAxiomFrameSection frame with inf
erred information: {}
java.lang.NullPointerException: null
        at org.mindswap.pellet.tableau.completion.rule.AllValuesRule.applyAllValues(AllValuesRule.java:200) ~[na:na]
        at org.mindswap.pellet.tableau.completion.CompletionStrategy.applyPropertyRestrictions(CompletionStrategy.java:603) ~
[na:na]
        at org.mindswap.pellet.tableau.completion.CompletionStrategy.addEdge(CompletionStrategy.java:583) ~[na:na]
        at org.mindswap.pellet.tableau.completion.rule.SomeValuesRule.applySomeValuesRule(SomeValuesRule.java:301) ~[na:na]
        at org.mindswap.pellet.tableau.completion.rule.SomeValuesRule.apply(SomeValuesRule.java:64) ~[na:na]
        at org.mindswap.pellet.tableau.completion.EmptySRIQStrategy.expand(EmptySRIQStrategy.java:303) ~[na:na]
        at org.mindswap.pellet.tableau.completion.EmptySRIQStrategy.complete(EmptySRIQStrategy.java:162) ~[na:na]
        at org.mindswap.pellet.ABox.isConsistent(ABox.java:1423) ~[na:na]
        at org.mindswap.pellet.ABox.isSatisfiable(ABox.java:595) ~[na:na]
        at org.mindswap.pellet.ABox.isSubClassOf(ABox.java:541) ~[na:na]
        at org.mindswap.pellet.taxonomy.CDOptimizedTaxonomyBuilder.subsumes(CDOptimizedTaxonomyBuilder.java:1210) ~[na:na]
        at org.mindswap.pellet.taxonomy.CDOptimizedTaxonomyBuilder.subCheckWithCache(CDOptimizedTaxonomyBuilder.java:1156) ~[
na:na]
        at org.mindswap.pellet.taxonomy.CDOptimizedTaxonomyBuilder.subsumed(CDOptimizedTaxonomyBuilder.java:1168) ~[na:na]
        at org.mindswap.pellet.taxonomy.CDOptimizedTaxonomyBuilder.doBottomSearch(CDOptimizedTaxonomyBuilder.java:944) ~[na:n
a]
        at org.mindswap.pellet.taxonomy.CDOptimizedTaxonomyBuilder.classify(CDOptimizedTaxonomyBuilder.java:878) ~[na:na]
        at org.mindswap.pellet.taxonomy.CDOptimizedTaxonomyBuilder.classify(CDOptimizedTaxonomyBuilder.java:265) ~[na:na]
        at org.mindswap.pellet.taxonomy.CDOptimizedTaxonomyBuilder.classify(CDOptimizedTaxonomyBuilder.java:218) ~[na:na]
        at org.mindswap.pellet.KnowledgeBase.classify(KnowledgeBase.java:2123) ~[na:na]

For the deadlock in "b":

Found one Java-level deadlock:
=============================
"Client-Server Communications":
  waiting to lock monitor 0x000000002fdfa248 (object 0x00000004d26f64d0, a java.util.HashMap),
  which is held by "AWT-EventQueue-0"
"AWT-EventQueue-0":
  waiting for ownable synchronizer 0x00000004d2904f10, (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync),
  which is held by "Client-Server Communications"

Java stack information for the threads listed above:
===================================================
"Client-Server Communications":
        at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl.getReasonerStatus(OWLReasonerManagerImpl.java:260)
        - waiting to lock <0x00000004d26f64d0> (a java.util.HashMap)
        at org.protege.editor.owl.model.OWLWorkspace.updateReasonerStatus(OWLWorkspace.java:789)
        at org.protege.editor.owl.model.OWLWorkspace.handleOntologiesChanged(OWLWorkspace.java:253)
        at org.protege.editor.owl.model.OWLWorkspace.access$100(OWLWorkspace.java:75)
        at org.protege.editor.owl.model.OWLWorkspace$1.ontologiesChanged(OWLWorkspace.java:115)
        at org.semanticweb.owlapi.model.DefaultChangeBroadcastStrategy.broadcastChanges(DefaultChangeBroadcastStrategy.java:38)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.broadcastChanges(OWLOntologyManagerImpl.java:1546)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.applyChanges(OWLOntologyManagerImpl.java:612)
        at org.protege.editor.owl.client.action.EnableAutoUpdateAction$AutoUpdate.performUpdate(EnableAutoUpdateAction.java:165)
        at org.protege.editor.owl.client.action.EnableAutoUpdateAction$AutoUpdate.run(EnableAutoUpdateAction.java:136)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
"AWT-EventQueue-0":
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000004d2904f10> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(Unknown Source)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(Unknown Source)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(Unknown Source)
        at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(Unknown Source)
        at uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl.hashCode(ConcurrentOWLOntologyImpl.java:81)
        at java.util.HashMap.hash(Unknown Source)
        at java.util.HashMap.get(Unknown Source)
        at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl.getCurrentReasoner(OWLReasonerManagerImpl.java:219)
        - locked <0x00000004d26f64d0> (a java.util.HashMap)
        at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl.getReasonerStatus(OWLReasonerManagerImpl.java:267)
        - locked <0x00000004d26f64d0> (a java.util.HashMap)
        at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$1$1.run(OWLReasonerManagerImpl.java:90)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by NCIEVS** [comment]
Below is a trace from [AG].  The NPE is different than the one from above.  The deadlock is more typical of the other deadlocks we've seen with the cell renderer.

hecking for updates
Pre-computing inferences:
    - class hierarchy
    - object property hierarchy
    - data property hierarchy
    - class assertions
    - object property assertions
    - same individuals
Checking for updates
Checking for updates
Checking for updates
Updating index with 23 change(s)
Checking for updates
Checking for updates
Checking for updates
Updating index with 12 change(s)
Checking for updates
Updating index with 7 change(s)
Checking for updates
Updating index with 8 change(s)
Checking for updates
Checking for updates
Checking for updates
Checking for updates
Checking for updates

An error occurred during reasoning: null.
java.lang.NullPointerException: null
        at org.mindswap.pellet.KnowledgeBase.realize(KnowledgeBase.java:2147) ~[
na:na]
        at com.clarkparsia.pellet.owlapiv3.PelletReasoner.precomputeInferences(P
elletReasoner.java:1058) ~[na:na]
        at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$Classif
icationRunner.precompute(OWLReasonerManagerImpl.java:447) ~[na:na]
        at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$Classif
icationRunner.run(OWLReasonerManagerImpl.java:388) ~[na:na]
        at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_102]
LOGBACK: No context given for org.protege.editor.core.log.LogManager$1[null]
Protege terminated reasoner.
Internal reasoner error: {}
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[na:1
.8.0_102]
        at java.util.ArrayList$Itr.next(Unknown Source) ~[na:1.8.0_102]
        at org.mindswap.pellet.tbox.impl.TermDefinition.updateDependencies(TermD
efinition.java:145) ~[na:na]
        at org.mindswap.pellet.tbox.impl.TermDefinition.addDef(TermDefinition.ja
va:92) ~[na:na]
        at org.mindswap.pellet.tbox.impl.TuBox.addDef(TuBox.java:81) ~[na:na]
        at org.mindswap.pellet.tbox.impl.TuBox.addIfUnfoldable(TuBox.java:253) ~
[na:na]
        at org.mindswap.pellet.tbox.impl.TBoxExpImpl.addAxiom(TBoxExpImpl.java:2
86) ~[na:na]
        at org.mindswap.pellet.tbox.impl.TBoxExpImpl.addAxiom(TBoxExpImpl.java:2
26) ~[na:na]
        at org.mindswap.pellet.KnowledgeBase.addSubClass(KnowledgeBase.java:650)
 ~[na:na]
        at com.clarkparsia.pellet.owlapiv3.PelletVisitor.visit(PelletVisitor.jav
a:656) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLSubClassOfAxiomImpl.accept(OWLSubCl
assOfAxiomImpl.java:117) ~[na:na]
        at com.clarkparsia.pellet.owlapiv3.PelletVisitor.visit(PelletVisitor.jav
a:837) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLImmutableOntologyImpl.accept(OWLImm
utableOntologyImpl.java:866) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl.a
ccept(ConcurrentOWLOntologyImpl.java:399) ~[na:na]
        at com.clarkparsia.pellet.owlapiv3.PelletReasoner.refresh(PelletReasoner
.java:956) ~[na:na]
        at com.clarkparsia.pellet.owlapiv3.PelletReasoner.refreshCheck(PelletRea
soner.java:973) ~[na:na]
        at com.clarkparsia.pellet.owlapiv3.PelletReasoner.isConsistent(PelletRea
soner.java:837) ~[na:na]
        at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl.getReas
onerStatus(OWLReasonerManagerImpl.java:272) ~[na:na]
        at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl.lambda$
classifyAsynchronously$0(OWLReasonerManagerImpl.java:311) ~[na:na]
        at java.lang.Thread.dispatchUncaughtException(Unknown Source) ~[na:1.8.0
_102]
An error occurred whilst rendering a token. Token: Organism; Token start index:
0
java.lang.NullPointerException: null
        at com.clarkparsia.pellet.owlapiv3.PelletReasoner.isConsistent(PelletRea
soner.java:839) ~[na:na]
        at org.protege.editor.owl.ui.renderer.OWLCellRenderer.lambda$renderToken
$0(OWLCellRenderer.java:781) [protege-editor-owl.jar:na]
        at org.protege.editor.owl.model.inference.DisplayedInferencePreferences.
executeTask(DisplayedInferencePreferences.java:118) ~[protege-editor-owl.jar:na]

        at org.protege.editor.owl.model.inference.ReasonerPreferences.executeTas
k(ReasonerPreferences.java:182) ~[protege-editor-owl.jar:na]
        at org.protege.editor.owl.ui.renderer.OWLCellRenderer.renderToken(OWLCel
lRenderer.java:778) [protege-editor-owl.jar:na]
        at org.protege.editor.owl.ui.renderer.OWLCellRenderer.highlightText(OWLC
ellRenderer.java:735) [protege-editor-owl.jar:na]
        at org.protege.editor.owl.ui.renderer.OWLCellRenderer.prepareTextPane(OW
LCellRenderer.java:707) [protege-editor-owl.jar:na]
        at org.protege.editor.owl.ui.renderer.OWLCellRenderer.prepareRenderer(OW
LCellRenderer.java:474) [protege-editor-owl.jar:na]
        at org.protege.editor.owl.ui.renderer.OWLCellRenderer.getTreeCellRendere
rComponent(OWLCellRenderer.java:354) [protege-editor-owl.jar:na]
        at org.protege.editor.owl.ui.tree.OWLObjectTreeCellRenderer.getTreeCellR
endererComponent(OWLObjectTreeCellRenderer.java:38) [protege-editor-owl.jar:na]
        at javax.swing.plaf.basic.BasicTreeUI.paintRow(Unknown Source) [na:1.8.0
_102]
        at javax.swing.plaf.basic.BasicTreeUI.paint(Unknown Source) [na:1.8.0_10
2]
        at javax.swing.plaf.ComponentUI.update(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paintComponent(Unknown Source) [na:1.8.0_102]
        at org.protege.editor.owl.ui.tree.OWLObjectTree.paintComponent(OWLObject
Tree.java:765) [protege-editor-owl.jar:na]
        at javax.swing.JComponent.paint(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paintChildren(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paint(Unknown Source) [na:1.8.0_102]
        at javax.swing.JViewport.paint(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paintChildren(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paint(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paintChildren(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paint(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paintChildren(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paint(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paintChildren(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paint(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paintChildren(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paint(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paintChildren(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paint(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paintChildren(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paint(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paintChildren(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paint(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paintChildren(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paint(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paintChildren(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paint(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paintChildren(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paint(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paintChildren(Unknown Source) [na:1.8.0_102]
        at javax.swing.JSplitPane.paintChildren(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paint(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paintChildren(Unknown Source) [na:1.8.0_102]
        at javax.swing.JSplitPane.paintChildren(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paint(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paintChildren(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paint(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paintChildren(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paint(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paintChildren(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paint(Unknown Source) [na:1.8.0_102]
        at javax.swing.JLayeredPane.paint(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paintChildren(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paintToOffscreen(Unknown Source) [na:1.8.0_102
]
        at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown S
ource) [na:1.8.0_102]
        at javax.swing.RepaintManager$PaintManager.paint(Unknown Source) [na:1.8
.0_102]
        at javax.swing.BufferStrategyPaintManager.paint(Unknown Source) [na:1.8.
0_102]
        at javax.swing.RepaintManager.paint(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.paint(Unknown Source) [na:1.8.0_102]
        at java.awt.GraphicsCallback$PaintCallback.run(Unknown Source) [na:1.8.0
_102]
        at sun.awt.SunGraphicsCallback.runOneComponent(Unknown Source) [na:1.8.0
_102]
        at sun.awt.SunGraphicsCallback.runComponents(Unknown Source) [na:1.8.0_1
02]
        at java.awt.Container.paint(Unknown Source) [na:1.8.0_102]
        at java.awt.Window.paint(Unknown Source) [na:1.8.0_102]
        at javax.swing.RepaintManager$4.run(Unknown Source) [na:1.8.0_102]
        at javax.swing.RepaintManager$4.run(Unknown Source) [na:1.8.0_102]
        at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_
102]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(Unknown Source) [na:1.8.0_102]
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source) [na:1.8.
0_102]
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source) [na:1.8.
0_102]
        at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source) [na:1
.8.0_102]
        at javax.swing.RepaintManager.access$1200(Unknown Source) [na:1.8.0_102]

        at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source) [na
:1.8.0_102]
        at java.awt.event.InvocationEvent.dispatch(Unknown Source) [na:1.8.0_102
]
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [na:1.8.0_102]
        at java.awt.EventQueue.access$500(Unknown Source) [na:1.8.0_102]
        at java.awt.EventQueue$3.run(Unknown Source) [na:1.8.0_102]
        at java.awt.EventQueue$3.run(Unknown Source) [na:1.8.0_102]
        at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_
102]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(Unknown Source) [na:1.8.0_102]
        at java.awt.EventQueue.dispatchEvent(Unknown Source) [na:1.8.0_102]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [
na:1.8.0_102]
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [na:
1.8.0_102]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [
na:1.8.0_102]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_102
]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_102
]
        at java.awt.EventDispatchThread.run(Unknown Source) [na:1.8.0_102]

**Comment by bdionne** [comment]
[reasoner.error.txt](https://github.com/NCIEVS/nci-protege5/files/1022985/reasoner.error.txt)

**Comment by NCIEVS** [comment]
This was observed when classification was being worked on for deployment.  A number of issues were fixed and this particular NPE hasn't been observed.  Will close with "wontfix".
