### ISSUE TITLE
Search hangs

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#27]
```
C:\NCI Applications\nci-protege5-build-09_08_2016>setlocal

C:\NCI Applications\nci-protege5-build-09_08_2016>cd /d C:\NCI Applications\nci-
protege5-build-09_08_2016\

C:\NCI Applications\nci-protege5-build-09_08_2016>.\jre1.8.0_91\bin\java -Xmx100
0M -Xms200M -Xss16M -XX:CompileCommand=exclude,javax/swing/text/GlyphView,getBre
akSpot -DentityExpansionLimit=100000000 -Dlogback.configurationFile=conf/logback
-win.xml -Dfile.encoding=utf-8 -Dorg.protege.plugin.dir=plugins -classpath bundl
es/guava.jar;bundles/logback-classic.jar;bundles/logback-core.jar;bundles/slf4j-
api.jar;bin/org.apache.felix.main.jar;bin/maven-artifact.jar;bin/protege-launche
r.jar org.protege.osgi.framework.Launcher
CompilerOracle: exclude javax/swing/text/GlyphView.getBreakSpot
********************************************************************************

**                                  Protege                                   **

********************************************************************************


----------------- Initialising and Starting the OSGi Framework -----------------

FrameworkFactory Class: org.apache.felix.framework.FrameworkFactory

The OSGi framework has been initialised
------------------------------- Starting Bundles -------------------------------

Starting bundle org.protege.common
Starting bundle org.eclipse.equinox.common
Starting bundle org.eclipse.equinox.supplement
Starting bundle org.eclipse.equinox.registry
Starting bundle org.protege.editor.core.application
Starting bundle org.apache.commons.io
Starting bundle com.google.guava
Not starting bundle com.google.inject.assistedinject explicitly because it is a
fragment bundle.
Not starting bundle com.google.inject.multibindings explicitly because it is a f
ragment bundle.
Starting bundle com.google.inject
Starting bundle jul.to.slf4j
Starting bundle log4j.over.slf4j
Starting bundle ch.qos.logback.classic
Starting bundle ch.qos.logback.core
Starting bundle org.apache.servicemix.bundles.aopalliance
Starting bundle org.apache.servicemix.bundles.javax-inject
Starting bundle org.eclipse.equinox.common
Starting bundle org.eclipse.equinox.registry
Starting bundle org.eclipse.equinox.supplement
Starting bundle org.semanticweb.owl.owlapi
Starting bundle org.protege.common
Starting bundle org.protege.editor.core.application
Starting bundle org.protege.editor.owl
Starting bundle slf4j.api
Starting bundle cellfie
Starting bundle com.clarkparsia.protege.plugin.pellet
Starting bundle csv-export-plugin
Starting bundle de.tu-dresden.inf.lat.jcel
Starting bundle existentialquery
Starting bundle it.unibz.inf.ontop.protege
Starting bundle org.protege.editor.search
Starting bundle lucene-search-tab
Starting bundle edu.stanford.protege.metaproject
Starting bundle nci-edit-tab
Starting bundle org.coode.browser
Starting bundle org.coode.change
Starting bundle org.coode.dlquery
Starting bundle org.coode.owlviz
Starting bundle org.exquisite.protege
Starting bundle org.protege.editor.owl.diff
Starting bundle org.protege.editor.owl.rdf
Starting bundle org.protege.ontograf
Starting bundle org.protege.owl.rdf
Starting bundle org.semanticweb.elk
Starting bundle OWLAx
Starting bundle org.protege.editor.owl.client
Starting bundle org.protege.editor.owl.server
Starting bundle ROWL
Starting bundle snap-sparql-query-plugin
Starting bundle swrltab-plugin
Starting bundle uk.ac.manchester.cs.owl.factplusplus
The OSGi framework has been started

------------------------------------ Protege -----------------------------------

Protege Desktop
Version 5.0.1, Build SNAPSHOT


----------------------------------- Platform -----------------------------------

Java: JVM 1.8.0_91-b15  Memory: 932M
Language: en, Country: US
Framework: Apache Software Foundation (1.7)
OS: windows7 (6.1)
Processor: x86-64


------------------------------------ Plugins -----------------------------------

Plugin: Cellfie Protege 5.0+ Plugin (2.0.0)
Plugin: Pellet Reasoner Plug-in (2.2.0)
Plugin: CSV Export Plugin (1.0.0.SNAPSHOT)
Plugin: jcel (0.23.2)
Plugin: Existential Query (2.0.0)
Plugin: Ontop OBDA Prot├⌐g├⌐ plugin (1.18.0)
Plugin: Lucene Search Plugin (1.0.0.SNAPSHOT)
Plugin: Lucene Search Tab (1.0.0.SNAPSHOT)
Plugin: metaproject (1.0.0.SNAPSHOT)
Plugin: Edit Tab (0.0.4.SNAPSHOT)
Plugin: Browser View (OWLDoc) (3.0.3)
Plugin: Change Tracker (2.0.2)
Plugin: DL Query (3.0.1)
Plugin: OWLViz (5.0.3)
Plugin: Ontology Debugger (0.1.1.BETA)
Plugin: OWL Difference (6.0.2)
Plugin: Protege SPARQL Plugin (2.0.1)
Plugin: OntoGraf (2.0.3)
Plugin: OWLAPI RDF Library (2.0.2)
Plugin: ELK Reasoner Protege Plug-in (0.4.3)
Plugin: OWLAx Protege 5.0+ Plugin (1.1.0)
Plugin: Protege Client (3.0.0.SNAPSHOT)
Plugin: Protege Server (3.0.0.SNAPSHOT)
Plugin: ROWL Protege 5.0+ Plugin (1.1.0)
Plugin: snap-sparql-query-plugin (4.1.0)
Plugin: SWRLTab Protege 5.0+ Plugin (1.1.2)
Plugin: Factplusplus Plug-in (1.6.4)

Creating and setting up empty (default) editor kit
OWL API Version: 4.2.5.20160517-0735
Loading default configuration parameters for class org.semanticweb.elk.reasoner.
config.ReasonerConfiguration
Cannot generate ontology catalog for ontology at http://www.semanticweb.org/garr
ettal/ontologies/2016/8/untitled-ontology-10
------------------------- Diagnosis Model Creation Settings --------------------
---------
Ontology: OntologyID(OntologyIRI(<http://www.semanticweb.org/garrettal/ontologie
s/2016/8/untitled-ontology-10>) VersionIRI(<null>))
OWLOntologyManager: uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl@159573
c6
OWLReasonerFactory: org.protege.editor.owl.model.inference.NoOpReasonerFactory@7
241fa85
OWLReasoner: org.protege.editor.owl.model.inference.NoOpReasoner@79aa0fd1
Configuration [extractModules]: false
Configuration [reduceIncoherency]: true
--------------------------------------------------------------------------------
---------
------------------------- Generated Diagnosis Model ----------------------------
---------
0 Possibly Faulty Formulas
0 Correct Formulas
0 Entailed Examples
0 Not-Entailed Examples
--------------------------------------------------------------------------------
---------
### Excluding compile: javax.swing.text.GlyphView::getBreakSpot
------------------------------- Auto-update Check ------------------------------

Auto-update last performed: Wed Sep 21 16:13:50 EDT 2016
Auto-update has been performed today.  Not performing it again.

Loaded ontology, now updating from server
Initializing index
Unable to open the ontology owlapi:ontology8879441008364
Exception thrown by listener: edu.stanford.protege.search.lucene.tab.engine.Sear
chTabManager$2.  Detatching bad listener.
------------------------- Diagnosis Model Creation Settings --------------------
---------
Ontology: OntologyID(OntologyIRI(<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus
.owl>) VersionIRI(<null>))
OWLOntologyManager: uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl@159573
c6
OWLReasonerFactory: org.protege.editor.owl.model.inference.NoOpReasonerFactory@4
22c0a2a
OWLReasoner: org.protege.editor.owl.model.inference.NoOpReasoner@5a832b65
Configuration [extractModules]: false
Configuration [reduceIncoherency]: true
--------------------------------------------------------------------------------
---------
------------------------- Generated Diagnosis Model ----------------------------
---------
168681 Possibly Faulty Formulas
0 Correct Formulas
0 Entailed Examples
0 Not-Entailed Examples
--------------------------------------------------------------------------------
---------
NCI Edit Tab initialized
Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.NullPointerException: null
        at org.apache.lucene.index.DirectoryReader.indexExists(DirectoryReader.j
ava:289) ~[na:na]
        at edu.stanford.protege.search.lucene.tab.engine.SearchTabManager.perfor
mSearch(SearchTabManager.java:245) ~[na:na]
        at edu.stanford.protege.search.lucene.tab.ui.QueryEditorPanel.lambda$new
$2(QueryEditorPanel.java:144) ~[na:na]
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) ~[na:1
.8.0_91]
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) ~[
na:1.8.0_91]
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) ~[
na:1.8.0_91]
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source) ~[na:1.8.0_
91]
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Sour
ce) ~[na:1.8.0_91]
        at java.awt.Component.processMouseEvent(Unknown Source) ~[na:1.8.0_91]
        at javax.swing.JComponent.processMouseEvent(Unknown Source) ~[na:1.8.0_9
1]
        at java.awt.Component.processEvent(Unknown Source) ~[na:1.8.0_91]
        at java.awt.Container.processEvent(Unknown Source) ~[na:1.8.0_91]
        at java.awt.Component.dispatchEventImpl(Unknown Source) ~[na:1.8.0_91]
        at java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:1.8.0_91]
        at java.awt.Component.dispatchEvent(Unknown Source) ~[na:1.8.0_91]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) ~[n
a:1.8.0_91]
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) ~[na
:1.8.0_91]
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) ~[na:1.8
.0_91]
        at java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:1.8.0_91]
        at java.awt.Window.dispatchEventImpl(Unknown Source) ~[na:1.8.0_91]
        at java.awt.Component.dispatchEvent(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventQueue.access$500(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventQueue$3.run(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventQueue$3.run(Unknown Source) ~[na:1.8.0_91]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0
_91]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(Unknown Source) ~[na:1.8.0_91]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventQueue$4.run(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventQueue$4.run(Unknown Source) ~[na:1.8.0_91]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0
_91]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [
na:1.8.0_91]
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [na:
1.8.0_91]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [
na:1.8.0_91]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_91]

        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_91]

        at java.awt.EventDispatchThread.run(Unknown Source) [na:1.8.0_91]
LOGBACK: No context given for org.protege.editor.core.log.LogManager$1[null]

```

**Comment by bdionne** [comment]
this looks like an [issue](https://github.com/protegeproject/lucene-search-tab/issues/4) in the search tab plugin

**Comment by NCIEVS** [comment]
This was a complex scenario with multiple plugins loaded and index directories moved from default locations, among other things.  Console output saved here.  Other search issues were fixed in parallel.  Will close-fix this one.
