### ISSUE TITLE
failure to paginate Lucene Search Tab search results after page 2

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#310]
From [EHD]:
"I was searching for OLD_PARENT property present. My protégé GUI is set to 500 results per page and this search yielded 852 results. When I went to the second page of results using the > button, I then browsed through a few of them. Then I tried to use the < button to get back to the first page of results. This gave me the following error in the console (twice because I hit the button again when it didn’t work the first time)"

From [GF]:
"It seems to happen going forward or backward after you’ve hit the second page in the list.  Mine is set to 50 per page, it’s the paging, seems to lose the correct page index when the page gets refreshed on page 2."

Below is the top of the stack trace.
Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.IndexOutOfBoundsException: Index: 2, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source) ~[na:1.8.0_102]
        at java.util.ArrayList.get(Unknown Source) ~[na:1.8.0_102]
        at edu.stanford.protege.search.lucene.tab.ui.QueryResultsPanel.lambda$7(QueryResultsPanel.java:234) ~[na:na]
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.processMouseEvent(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.JComponent.processMouseEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.processEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Container.processEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]

**Comment by bdionne** [comment]
[fixed in 1.0.7](https://github.com/bdionne/lucene-search-tab/releases/tag/lucene-search-tab-1.0.7)

**Comment by rmehri** [comment]
Hi, 
This fix has been retested and verified using tag 1.007, Lucene Search Tab 1.0.7.  Please see attached snapshots for more details.

![issue-310-1](https://user-images.githubusercontent.com/8367102/28035899-46b96856-6584-11e7-8cf8-ea3357bd0f0c.png)
![issue-310-2](https://user-images.githubusercontent.com/8367102/28035900-46b98b9c-6584-11e7-8866-350d60afc31d.png)
![issue-310-3](https://user-images.githubusercontent.com/8367102/28035901-46bc616e-6584-11e7-96ad-593189bee6cf.png)
![issue-310-4](https://user-images.githubusercontent.com/8367102/28035902-46be8d36-6584-11e7-80b5-1bf0b8446711.png)
![issue-310-5](https://user-images.githubusercontent.com/8367102/28035898-46b70b88-6584-11e7-9f5c-0b67ae7a88f6.png)

Thanks,
Reza
