### ISSUE TITLE
failure to generate concept history

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#328]
The squash had proceeded prior to concept history processing and the archive with the snapshots did get generated.

On clicking the "History" button, the client console showed the message “Server failed to generate concept history”.  ncitconcept_history was created; however, what didn't happen was the creation of the history archive directory to move/copy the history files there.  All the archivable files were in the prod server and had a correct range of dates.

The top of the stack trace on the exception thrown on the client during history concept generation was:

Server failed to generate concept history (contact server admin for further assi
stance)
org.protege.editor.owl.client.api.exception.ClientRequestException: Server faile
d to generate concept history (contact server admin for further assistance)
        at org.protege.editor.owl.client.LocalHttpClient.throwRequestExceptions(
LocalHttpClient.java:874) ~[protege-client-3.0.0-SNAPSHOT.jar:na]
        at org.protege.editor.owl.client.LocalHttpClient.get(LocalHttpClient.jav
a:753) ~[protege-client-3.0.0-SNAPSHOT.jar:na]
        at org.protege.editor.owl.client.LocalHttpClient.genConceptHistory(Local
HttpClient.java:832) ~[protege-client-3.0.0-SNAPSHOT.jar:na]
        at org.protege.editor.owl.client.diff.ui.ReviewButtonsPanel$5.actionPerf
ormed(ReviewButtonsPanel.java:227) [revision-history-1.0.5.jar:na]
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) [na:1.
8.0_102]
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) [n
a:1.8.0_102]
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) [n
a:1.8.0_102]
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source) [na:1.8.0_1
02]
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Sour
ce) [na:1.8.0_102]
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source) [na:1.8.0_
102]
        at java.awt.Component.processMouseEvent(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.processMouseEvent(Unknown Source) [na:1.8.0_10
2]
        at java.awt.Component.processEvent(Unknown Source) [na:1.8.0_102]
        at java.awt.Container.processEvent(Unknown Source) [na:1.8.0_102]
        at java.awt.Component.dispatchEventImpl(Unknown Source) [na:1.8.0_102]
        at java.awt.Container.dispatchEventImpl(Unknown Source) [na:1.8.0_102]
        at java.awt.Component.dispatchEvent(Unknown Source) [na:1.8.0_102]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) [na
:1.8.0_102]
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) [na:
1.8.0_102]
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) [na:1.8.
0_102]

**Comment by bdionne** [comment]
Was this on the production system?

By any chance is there a server log we can look at?

I've tried this a couple of times and it works ok, locally.  If the concept history was actually created on the server, but not copied to the archive, then I would suspect there's a configuration/permissions issue preventing the creation of the new directories. 

I've looked at the config on the dev and qa tier and they seems ok, but I don't see any very recent activity either so I'm guessing this is on another tier?

**Comment by NCIEVS** [comment]
Yes, this is in PROD.  Just got a copy of the logs, will send you the URL separately.

I thought the same about the permissions, except that the squashing went well, and the baseline from the last month proceeded well on both the squashing and the concept history archiving fronts.

**Comment by bdionne** [comment]
This is due to bad data (see #330 )

**Comment by NCIEVS** [comment]
Triaging for fy 2019.  low priority, keep under future release until backlog clears.
