### ISSUE TITLE
Pellet server error

### ISSUE THREAD

**Issue by safrant** [NCIEVS/nci-protege5#339]
![pellet_error_nov22](https://user-images.githubusercontent.com/2364871/33143358-a8427956-cf87-11e7-8bb5-bcff610175d1.jpeg)

**Comment by bdionne** [comment]
Pellet reasoner messes up classifying large Thesaurus under a couple of scenarios:

````

Protege terminated reasoner.
Internal reasoner error: {}
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: Request call failed: [500] Internal Server Error
       at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203) ~[guava.jar:na]
       at com.google.common.cache.LocalCache.get(LocalCache.java:3937) ~[guava.jar:na]
       at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941) ~[guava.jar:na]
       at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824) ~[guava.jar:na]
       at com.complexible.pellet.client.reasoner.RemoteSchemaReasoner.query(RemoteSchemaReasoner.java:67) ~[na:na]
       at com.complexible.pellet.client.reasoner.SchemaOWLReasoner.executeQuery(SchemaOWLReasoner.java:121) ~[na:na]
       at com.complexible.pellet.client.reasoner.SchemaOWLReasoner.executeSingletonQuery(SchemaOWLReasoner.java:112) ~[na:na]
       at com.complexible.pellet.client.reasoner.SchemaOWLReasoner.getEquivalentClasses(SchemaOWLReasoner.java:175) ~[na:na]
       at com.complexible.pellet.client.reasoner.SchemaOWLReasoner.getBottomClassNode(SchemaOWLReasoner.java:195) ~[na:na]
       at com.complexible.pellet.client.reasoner.SchemaOWLReasoner.getUnsatisfiableClasses(SchemaOWLReasoner.java:569) ~[na:na]
       at 

````

**Comment by bdionne** [comment]
I've added the [Thesaurus](https://github.com/NCIEVS/nci-protege5/tree/master/data) owl file we're using to test on DEV/QA to the project, which we can use for reproducing results.

@safrant @NCIEVS - on my large Mac I'm not able to reproduce this. I run Pellet with 12G of ram, protege server with 6G and two clients with 8G. I"m also not able to reproduce it using small base.

Interestingly this content classifies in about 8 minutes. Perhaps you pushed a different file? It has about 120K classes and 200K axioms, and all the foobar tests so I think it's correct, about 430M on disk.

I suspect the issue relates to the serialized snapshot. The tests you ran on DEV were using a project built earlier and not with the new version? @safrant, if this is the case can you please try the same test but create a new project first? That's the only difference I see with what we did on DEV and what I tried locally. In a way I hope it's not the case as I can't imagine what changed with the classes to affect serialization.

**Comment by safrant** [comment]
Will it be a problem using the previous project as a template?

Tracy M. Safran
Programmer Analyst - EVS support
Frederick National Laboratory for Cancer Research
Leidos Biomedical Research, Inc.
Ph: 240-276-5172
Tracy.Safran@fnlcr.nih.gov<mailto:Tracy.Safran@fnlcr.nih.gov>

**Comment by bdionne** [comment]
It should be ok, I would go back to the copied one though and delete the `classifiable:true` option so that pellet doesn't try to classify two large projects

**Comment by safrant** [comment]
I deleted the contents or protegedata/pelletdata and I created a new project from the Foo file I sent you.  It did classify in about 8 minutes, as you noted.
I then went to the client, started the reasoner, and applied the classification suggestions. It came back with a familiar 500 error.

This was on the server:

Extracting finished in 00:00:07.679
Nov 24, 2017 12:23:00 PM com.clarkparsia.modularity.AbstractModuleExtractor updateEffectedModules
SEVERE: No module for <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C20201017>
java.lang.RuntimeException: No module for <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C20201017>
                at com.clarkparsia.modularity.AbstractModuleExtractor.updateEffectedModules(AbstractModuleExtractor.java:523)
                at com.clarkparsia.modularity.AbstractModuleExtractor.applyChanges(AbstractModuleExtractor.java:543)
                at com.clarkparsia.modularity.IncrementalReasoner.incClassifyAllModStrategy(IncrementalReasoner.java:383)
                at com.clarkparsia.modularity.IncrementalReasoner.incrementalClassify(IncrementalReasoner.java:434)
                at com.clarkparsia.modularity.IncrementalReasoner.classify(IncrementalReasoner.java:320)
                at com.clarkparsia.modularity.IncrementalReasoner.getEquivalentClasses(IncrementalReasoner.java:341)
                at com.clarkparsia.pellet.server.reasoner.LocalSchemaReasoner$ClassQueryEvaluator.query(LocalSchemaReasoner.java:148)
                at com.clarkparsia.pellet.server.reasoner.LocalSchemaReasoner.query(LocalSchemaReasoner.java:72)
                at com.clarkparsia.pellet.server.handlers.ReasonerQueryHandler.handleRequest(ReasonerQueryHandler.java:33)
                at io.undertow.server.Connectors.executeRootHandler(Connectors.java:198)
                at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:788)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)

Extracting:  100% complete in 00:00:00.000
Extracting finished in 00:00:05.131


Tracy M. Safran
Programmer Analyst - EVS support
Frederick National Laboratory for Cancer Research
Leidos Biomedical Research, Inc.
Ph: 240-276-5172
Tracy.Safran@fnlcr.nih.gov<mailto:Tracy.Safran@fnlcr.nih.gov>

**Comment by bdionne** [comment]
Interesting, I can't seem to reproduce that particular stack trace. I just tried your new scenario -- made a new project by copying the previous one, brought up pellet to classify it, brought up the client, saw the suggestions and fixed them. This is what the pellet server sees:

<img width="1354" alt="screen shot 2017-11-24 at 12 48 54 pm" src="https://user-images.githubusercontent.com/31741/33220412-fd688bde-d115-11e7-9c57-39103440c59d.png">

**Comment by safrant** [comment]
The classification suggestions were applied successfully, and I have been able to toddle along since without a problem.

Tracy M. Safran
Programmer Analyst - EVS support
Frederick National Laboratory for Cancer Research
Leidos Biomedical Research, Inc.
Ph: 240-276-5172
Tracy.Safran@fnlcr.nih.gov<mailto:Tracy.Safran@fnlcr.nih.gov>

**Comment by bdionne** [comment]
@safrant - I'm still not able to reproduce that 500, have you seen it again since? Are you able to classify and use the results panel?

**Comment by safrant** [comment]
I am.  I can hit it a little harder to see if it breaks, but I haven’t seen any issues since I accepted the foo suggestions.

Tracy M. Safran
Programmer Analyst - EVS support
Frederick National Laboratory for Cancer Research
Leidos Biomedical Research, Inc.
Ph: 240-276-5172
Tracy.Safran@fnlcr.nih.gov<mailto:Tracy.Safran@fnlcr.nih.gov>

**Comment by safrant** [comment]
OK, I managed to break it again.

Tracy M. Safran
Programmer Analyst - EVS support
Frederick National Laboratory for Cancer Research
Leidos Biomedical Research, Inc.
Ph: 240-276-5172
Tracy.Safran@fnlcr.nih.gov<mailto:Tracy.Safran@fnlcr.nih.gov>


From: Tracy Safran <safrant@mail.nih.gov>
Date: Monday, November 27, 2017 at 11:18 AM
To: NCIEVS/nci-protege5 <reply@reply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: Re: [NCIEVS/nci-protege5] Pellet server error (#339)

I am.  I can hit it a little harder to see if it breaks, but I haven’t seen any issues since I accepted the foo suggestions.

Tracy M. Safran
Programmer Analyst - EVS support
Frederick National Laboratory for Cancer Research
Leidos Biomedical Research, Inc.
Ph: 240-276-5172
Tracy.Safran@fnlcr.nih.gov<mailto:Tracy.Safran@fnlcr.nih.gov>

**Comment by bdionne** [comment]
great, by chance do you remember the scenario?

**Comment by safrant** [comment]
I am glad you asked!  Attached are the notes I was taking as I went along.

P.S.  I checked my account and I see no link to Craig’s email anywhere.

Tracy M. Safran
Programmer Analyst - EVS support
Frederick National Laboratory for Cancer Research
Leidos Biomedical Research, Inc.
Ph: 240-276-5172
Tracy.Safran@fnlcr.nih.gov<mailto:Tracy.Safran@fnlcr.nih.gov>

**Comment by NCIEVS** [comment]
I was thinking the second email address was attached to Craig’s entry.  Well, that’s a mystery!

**Comment by bdionne** [comment]
@NCIEVS @safrant - I believe that's just the notification email acct. it's a noop

@safrant - I thin there's some confusion about the way the reasoner now works. You will no longer see updates immediately. You'll see them after you select `Synchronize Reasoner` in the `Reasoner` menu. So in your specific case you won't see `owl:Nothing` disappear when you fix the error until you:

* save the edit
* synchronize the reasoner, to pick up the changes from Pellet.

This approach is simpler, and Nick seemed to prefer this manual syncing, at least at a first pass.

I don't know what this other exception you see, I'll reproduce it locally and see.

I did find a way to generate a `500` from the server, but it seems like a different scenario from this ticket.

**Comment by bdionne** [comment]
@safrant -- one of the exceptions you see when trying to remove `owl:Nothing` is due to it being editable, I opened a separate ticket for it ( #340 ).

**Comment by bdionne** [comment]
I smoke tested V2.1.0.12 and it looked ok, I'm running it now using Thesaurus and so far I'm not seeing any `500` or other errors.
