### ISSUE TITLE
Protege client sees 500 errors when Pellet times out

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#341]
Not sure this is related to #339 or not, but a `500` occurs in the following scenario:

* start pellet and let it classify the ontology
* start a protege client
* start the reasoner, perform some edits, synchronize and see the results from pellet
* stop working for 30 minutes and get a coffee
* resume and perform edits and synchronize reasoner
* possibly see `500` as below.

When client connection between protege and pellet times out (default is 30 minutes of inactivity) subsequent calls results in null pointer errors on the server that are swallowed and a `500` is returned.

````
Internal reasoner error: {}
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: Request call failed: [500] Internal Server Error
at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203) ~[guava.jar:na]
at com.google.common.cache.LocalCache.get(LocalCache.java:3937) ~[guava.jar:na]
at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941) ~[guava.jar:na]
at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824) ~[guava.jar:na]
at com.complexible.pellet.client.reasoner.RemoteSchemaReasoner.query(RemoteSchemaReasoner.java:67) ~[na:na]
at com.complexible.pellet.client.reasoner.SchemaOWLReasoner.executeQuery(SchemaOWLReasoner.java:121) ~[na:na]
at com.complexible.pellet.client.reasoner.SchemaOWLReasoner.executeSingletonQuery(SchemaOWLReasoner.java:112) ~[na:na]
at com.complexible.pellet.client.reasoner.SchemaOWLReasoner.getEquivalentClasses(SchemaOWLReasoner.java:175) ~[na:na]
at com.complexible.pellet.client.reasoner.SchemaOWLReasoner.getBottomClassNode(SchemaOWLReasoner.java:195) ~[na:na]
````

**Comment by bdionne** [comment]
Fixed in [V2.1.0.012](https://github.com/bdionne/pellet/commit/46f534449c8bb1fbea1f82bcbe859fdd72ab2c50)

**Comment by kondareddys2** [comment]
Performed the following steps:

1.start pellet and let it classify the ontology
2.start a protege client
3.start the reasoner, perform some edits, synchronize and see the results from pellet
4.stop working for 30 minutes and get a coffee
5.resume and perform edits and synchronize reasoner

Do not see a 500 error.

But the save button is disabled after performing edits on properties.

**Comment by kondareddys2** [comment]
closing the defect as we do not see any 500 error.
