### ISSUE TITLE
warnings thrown when building pellet

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#35]
Not clear whether this affects pellet.  There are other issues with it currently in the client-server environment but can't say what's the impact of these two build warnings (both related to antlr).  Below is the entire output for the build of this component.

[INFO] Building Pellet :: Query 2.4.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ pellet-query ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ pellet-query ---
[INFO]
[INFO] --- antlr3-maven-plugin:3.5.1:antlr (default) @ pellet-query ---
[INFO] ANTLR: Processing source directory /local/project/nciedittab-dev12/nci-protege5/scripts/nci-protege5/pellet/query/src/main/antlr3
ANTLR Parser Generator  Version 3.5.1
Output file /local/project/nciedittab-dev12/nci-protege5/scripts/nci-protege5/pellet/query/target/generated-sources/antlr3/com/clarkparsia/sparqlowl/parser/antlr/SparqlOwlParser.java does not exist: must build /local/project/nciedittab-dev12/nci-protege5/scripts/nci-protege5/pellet/query/src/main/antlr3/com/clarkparsia/sparqlowl/parser/antlr/SparqlOwl.g
com/clarkparsia/sparqlowl/parser/antlr/SparqlOwl.g
warning(24):  template error: context [/outputFile /parser /genericParser /region__/genericParser__members /region__/genericParser__members] 32:3 no such property or can't access: org.antlr.tool.Grammar.indirectDelegates
Caused by: org.stringtemplate.v4.misc.STNoSuchPropertyException: no such property: org.antlr.tool.Grammar.indirectDelegates
        at org.stringtemplate.v4.misc.ObjectModelAdaptor.throwNoSuchProperty(ObjectModelAdaptor.java:106)
        at org.stringtemplate.v4.misc.ObjectModelAdaptor.lookupMethod(ObjectModelAdaptor.java:99)
        at org.stringtemplate.v4.misc.ObjectModelAdaptor.getProperty(ObjectModelAdaptor.java:67)
        at org.stringtemplate.v4.Interpreter.getObjectProperty(Interpreter.java:1158)
        at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:210)
        at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
        at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:703)
        at org.stringtemplate.v4.Interpreter.writeObjectNoOptions(Interpreter.java:635)
        at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:285)
        at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
        at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:703)
        at org.stringtemplate.v4.Interpreter.writeObjectNoOptions(Interpreter.java:635)
        at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:285)
        at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
        at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:703)
        at org.stringtemplate.v4.Interpreter.writeObjectNoOptions(Interpreter.java:635)
        at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:285)
        at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
        at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:703)
        at org.stringtemplate.v4.Interpreter.writeObjectNoOptions(Interpreter.java:635)
        at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:285)
        at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
        at org.stringtemplate.v4.ST.write(ST.java:415)
        at org.antlr.codegen.CodeGenerator.write(CodeGenerator.java:1296)
        at org.antlr.codegen.Target.genRecognizerFile(Target.java:98)
        at org.antlr.codegen.CodeGenerator.genRecognizer(CodeGenerator.java:459)
        at org.antlr.Tool.generateRecognizer(Tool.java:674)
        at org.antlr.Tool.process(Tool.java:487)
        at org.antlr.mojo.antlr3.Antlr3Mojo.execute(Antlr3Mojo.java:380)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.stringtemplate.v4.misc.Misc.invokeMethod(Misc.java:218)
        at org.stringtemplate.v4.misc.ObjectModelAdaptor.lookupMethod(ObjectModelAdaptor.java:84)
        ... 48 more
Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at java.util.ArrayList.removeAll(ArrayList.java:689)
        at org.antlr.tool.CompositeGrammar.getIndirectDelegates(CompositeGrammar.java:226)
        at org.antlr.tool.Grammar.getIndirectDelegates(Grammar.java:2722)
        ... 54 more

Output file /local/project/nciedittab-dev12/nci-protege5/scripts/nci-protege5/pellet/query/target/generated-sources/antlr3/com/clarkparsia/sparqlowl/parser/antlr/SparqlOwlTreeARQ.java does not exist: must build /local/project/nciedittab-dev12/nci-protege5/scripts/nci-protege5/pellet/query/src/main/antlr3/com/clarkparsia/sparqlowl/parser/antlr/SparqlOwlTreeARQ.g
com/clarkparsia/sparqlowl/parser/antlr/SparqlOwlTreeARQ.g
warning(24):  template error: context [/outputFile /treeParser /genericParser /region__/genericParser__members] 32:3 no such property or can't access: org.antlr.tool.Grammar.indirectDelegates
Caused by: org.stringtemplate.v4.misc.STNoSuchPropertyException: no such property: org.antlr.tool.Grammar.indirectDelegates
        at org.stringtemplate.v4.misc.ObjectModelAdaptor.throwNoSuchProperty(ObjectModelAdaptor.java:106)
        at org.stringtemplate.v4.misc.ObjectModelAdaptor.lookupMethod(ObjectModelAdaptor.java:99)
        at org.stringtemplate.v4.misc.ObjectModelAdaptor.getProperty(ObjectModelAdaptor.java:67)
        at org.stringtemplate.v4.Interpreter.getObjectProperty(Interpreter.java:1158)
        at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:210)
        at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
        at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:703)
        at org.stringtemplate.v4.Interpreter.writeObjectNoOptions(Interpreter.java:635)
        at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:285)
        at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
        at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:703)
        at org.stringtemplate.v4.Interpreter.writeObjectNoOptions(Interpreter.java:635)
        at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:285)
        at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
        at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:703)
        at org.stringtemplate.v4.Interpreter.writeObjectNoOptions(Interpreter.java:635)
        at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:285)
        at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
        at org.stringtemplate.v4.ST.write(ST.java:415)
        at org.antlr.codegen.CodeGenerator.write(CodeGenerator.java:1296)
        at org.antlr.codegen.Target.genRecognizerFile(Target.java:98)
        at org.antlr.codegen.CodeGenerator.genRecognizer(CodeGenerator.java:459)
        at org.antlr.Tool.generateRecognizer(Tool.java:674)
        at org.antlr.Tool.process(Tool.java:487)
        at org.antlr.mojo.antlr3.Antlr3Mojo.execute(Antlr3Mojo.java:380)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.stringtemplate.v4.misc.Misc.invokeMethod(Misc.java:218)
        at org.stringtemplate.v4.misc.ObjectModelAdaptor.lookupMethod(ObjectModelAdaptor.java:84)
        ... 44 more
Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at java.util.ArrayList.removeAll(ArrayList.java:689)
        at org.antlr.tool.CompositeGrammar.getIndirectDelegates(CompositeGrammar.java:226)
        at org.antlr.tool.Grammar.getIndirectDelegates(Grammar.java:2722)
        ... 50 more

[INFO]
[INFO] --- build-helper-maven-plugin:1.8:add-source (add-source) @ pellet-query ---
[INFO] Source directory: /local/project/nciedittab-dev12/nci-protege5/scripts/nci-protege5/pellet/query/target/generated-sources/antlr3 added.
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ pellet-query ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /local/project/nciedittab-dev12/nci-protege5/scripts/nci-protege5/pellet/query/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ pellet-query ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 18 source files to /local/project/nciedittab-dev12/nci-protege5/scripts/nci-protege5/pellet/query/target/classes
[WARNING] /local/project/nciedittab-dev12/nci-protege5/scripts/nci-protege5/pellet/query/src/main/java/com/clarkparsia/pellet/sparqldl/jena/JenaIOUtils.java: Some input files use or override a deprecated API.
[WARNING] /local/project/nciedittab-dev12/nci-protege5/scripts/nci-protege5/pellet/query/src/main/java/com/clarkparsia/pellet/sparqldl/jena/JenaIOUtils.java: Recompile with -Xlint:deprecation for details.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ pellet-query ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /local/project/nciedittab-dev12/nci-protege5/scripts/nci-protege5/pellet/query/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ pellet-query ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.16:test (default-test) @ pellet-query ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ pellet-query ---
[INFO] Building jar: /local/project/nciedittab-dev12/nci-protege5/scripts/nci-protege5/pellet/query/target/pellet-query-2.4.0-SNAPSHOT.jar
[INFO]
[INFO] --- maven-jar-plugin:2.4:test-jar (default) @ pellet-query ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: /local/project/nciedittab-dev12/nci-protege5/scripts/nci-protege5/pellet/query/target/pellet-query-2.4.0-SNAPSHOT-tests.jar
[INFO]
[INFO] --- maven-install-plugin:2.5.1:install (default-install) @ pellet-query ---
[INFO] Installing /local/project/nciedittab-dev12/nci-protege5/scripts/nci-protege5/pellet/query/target/pellet-query-2.4.0-SNAPSHOT.jar to /home/protegeadm/.m2/repository/com/clarkparsia/pellet/pellet-query/2.4.0-SNAPSHOT/pellet-query-2.4.0-SNAPSHOT.jar
[INFO] Installing /local/project/nciedittab-dev12/nci-protege5/scripts/nci-protege5/pellet/query/pom.xml to /home/protegeadm/.m2/repository/com/clarkparsia/pellet/pellet-query/2.4.0-SNAPSHOT/pellet-query-2.4.0-SNAPSHOT.pom
[INFO] Installing /local/project/nciedittab-dev12/nci-protege5/scripts/nci-protege5/pellet/query/target/pellet-query-2.4.0-SNAPSHOT-tests.jar to /home/protegeadm/.m2/repository/com/clarkparsia/pellet/pellet-query/2.4.0-SNAPSHOT/pellet-query-2.4.0-SNAPSHOT-tests.jar

**Comment by bdionne** [comment]
seems harmless, probably need an antlr upgrade, server and classifier still seem to run correctly

**Comment by bdionne** [comment]
This is a build issue related to antlr, no impact on system

**Comment by NCIEVS** [comment]
This seems to have been reopened accidentally.  Closing again.
