### ISSUE TITLE
Remote Server Classifier Missed an Edit and was Not Restarted with Restart Remote Reasoner

### ISSUE THREAD

**Issue by hahndane** [NCIEVS/nci-protege5#362]
On the prod server in early February, the remote classifer missed an edit and thought that a recently created and then retired concept had a live concept as a parent and that it still had active concepts as children (so it and its past children were labeled inconsistent). The menu commands to Synchronize reasoner and Restart Remote Reasoner did not update the inferences. 

A few days later when I checked again, newly created classes had not been integrated into the inferred hierarchy. So not only was an edit (or set of edits) missed but some time later subsequent edits had failed to be included.

**Comment by safrant** [comment]
What I have discovered by testing on QA:  Restarting reasoner remotely will cause reasoner to go through classify and extracting,  but does not lead to a server available message, even after an hour.  Attempts to do reasoning leads to the message Liz reported. 
![image](https://user-images.githubusercontent.com/2364871/37542237-e28a736a-2933-11e8-930d-4fbacb39256a.png)

**Comment by safrant** [comment]
Further investigation - on QA, did a number of edits and successive reasoner refreshes. It missed some edits that weren't caught, then stopped catching things altogether.  Went on server to restart and eventually reasoner hit a java heap error and explanation server didn't start.  Currently set at 10 gigs.

**Comment by singhik** [comment]
@bdionne : Hi, Unable to start Reasoner , throws 'Internal reasoner error ' prompt ::

![image](https://user-images.githubusercontent.com/36314371/42590117-ed18e49a-8510-11e8-89db-a21dcc71c951.png)


Logs ::

[Logs.txt.txt](https://github.com/NCIEVS/nci-protege5/files/2185620/Logs.txt.txt)

**Comment by NCIEVS** [comment]
The URL is wrong, it should be a secure https site rather than http.  In the File->Prefefrences... set the remote pellet URL to use https.  (@safrant please note this for the file preferences.)

**Comment by singhik** [comment]
@NCIEVS :: Hi, updated the Remote Peller URL with https, restarted client but still see the 'Internal Reasoner  Error' prompt message , logs are below ::

![image](https://user-images.githubusercontent.com/36314371/42593537-bae69170-851a-11e8-87d4-d7e5f512eafe.png)

![image](https://user-images.githubusercontent.com/36314371/42593600-ed7ef69a-851a-11e8-9035-f9432a5cd9d8.png)


Logs ::

Caused by: java.net.ConnectException: Failed to connect to nciws-q791-v.nci.nih.gov/10.133.106.121:18080
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:222) ~[na:na]
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:146) ~[na:na]
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:186) ~[na:na]
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121) ~[na:na]
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100) ~[na:na]
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) ~[na:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[na:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[na:na]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[na:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[na:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[na:na]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[na:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[na:na]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120) ~[na:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[na:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[na:na]
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179) ~[na:na]
        at okhttp3.RealCall.execute(RealCall.java:63) ~[na:na]
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:118) ~[na:na]
        at com.complexible.pellet.client.ClientTools.executeCall(ClientTools.java:22) ~[na:na]
        ... 40 common frames omitted
Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[na:1.8.0_102]
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[na:1.8.0_102]
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[na:1.8.0_102]
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[na:1.8.0_102]
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_102]
        at java.net.PlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_102]
        at java.net.SocksSocketImpl.connect(Unknown Source) ~[na:1.8.0_102]
        at java.net.Socket.connect(Unknown Source) ~[na:1.8.0_102]
        at okhttp3.internal.platform.Platform.connectSocket(Platform.java:124) ~[na:na]
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:220) ~[na:na]

**Comment by singhik** [comment]
QA has verified multiple Creations, Editions,Retire operations and all have been visible in Revision History post "Reasoner" was manually started. There  was also not any Reasoner Start/Reasoner Synchronize Error noticed . Attached is the document with screen prints ....

[Issue 362.docx](https://github.com/NCIEVS/nci-protege5/files/2198683/Issue.362.docx)
