### ISSUE TITLE
Error and then Role Restrictions turn Pink

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#382]
From [EHD]:
"I was trying to use a restriction filler value on a new concept to see the modeling on that filler value concept.   [I clicked on a restriction filler value to navigate to the class being used as a **filler.**]   I got the following error and then the restrictions turned pink:"

"The GUI is still functional and I can still add roles, it’s just a jarring color now. (I have had this happen before but I never saw/captured an associated error message.)"

[from @ncievs - image below, java exception further below.]

![ehd-roles-on-new](https://user-images.githubusercontent.com/7783321/39332782-842e17e6-4976-11e8-8083-ee939ebbcdf6.png)
java.lang.ArrayIndexOutOfBoundsException: -1
        at javax.swing.text.CompositeView.getView(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.text.FlowView$FlowStrategy.createView(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.text.FlowView$FlowStrategy.layoutRow(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.text.FlowView$FlowStrategy.layout(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.text.FlowView.layout(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.text.BoxView.setSize(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.text.BoxView.updateChildSizes(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.text.BoxView.setSpanOnAxis(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.text.BoxView.layout(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.text.BoxView.setSize(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.plaf.basic.BasicTextUI$RootView.setSize(Unknown Source) ~[na:1.8.0_102]
        at org.protege.editor.owl.ui.renderer.OWLCellRenderer$OWLCellRendererLayoutManager.preferredLayoutSize(OWLCellRenderer.java:1031) ~[protege-ed
itor-owl.jar:na]
        at java.awt.Container.preferredSize(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Container.getPreferredSize(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.JComponent.getPreferredSize(Unknown Source) ~[na:1.8.0_102]
        at org.protege.editor.core.ui.list.MList$MListCellRenderer.getListCellRendererComponent(MList.java:268) ~[protege-editor-core.jar:na]
        at org.protege.editor.owl.ui.framelist.OWLFrameList$OWLFrameListUI.updateLayoutState(OWLFrameList.java:947) ~[protege-editor-owl.jar:na]
        at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.DefaultListSelectionModel.removeSelectionIntervalImpl(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.DefaultListSelectionModel.clearSelection(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.JList.clearSelection(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.JList.setModel(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.JList.setListData(Unknown Source) ~[na:1.8.0_102]
        at org.protege.editor.owl.ui.framelist.OWLFrameList.refillRows(OWLFrameList.java:411) ~[protege-editor-owl.jar:na]
        at org.protege.editor.owl.ui.framelist.OWLFrameList.lambda$setupFrameListener$5(OWLFrameList.java:234) ~[protege-editor-owl.jar:na]
        at org.protege.editor.owl.ui.frame.AbstractOWLFrame.fireContentChanged(AbstractOWLFrame.java:113) ~[protege-editor-owl.jar:na]
        at org.protege.editor.owl.ui.frame.AbstractOWLFrameSection.fireContentChanged(AbstractOWLFrameSection.java:327) [protege-editor-owl.jar:na]
        at org.protege.editor.owl.ui.frame.AbstractOWLFrameSection.setRootObject(AbstractOWLFrameSection.java:283) [protege-editor-owl.jar:na]
        at org.protege.editor.owl.ui.frame.AbstractOWLFrameSection.reset(AbstractOWLFrameSection.java:321) [protege-editor-owl.jar:na]
        at org.protege.editor.owl.ui.frame.AbstractOWLFrameSection.processOntologyChanges(AbstractOWLFrameSection.java:93) [protege-editor-owl.jar:na]
        at org.protege.editor.owl.ui.frame.AbstractOWLFrameSection.lambda$new$0(AbstractOWLFrameSection.java:54) [protege-editor-owl.jar:na]
        at org.semanticweb.owlapi.model.DefaultChangeBroadcastStrategy.broadcastChanges(DefaultChangeBroadcastStrategy.java:38) ~[owlapi-osgidistribut
ion.jar:4.2.8-SNAPSHOT.2018-04-02T21:25:49Z]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.broadcastChanges(OWLOntologyManagerImpl.java:1537) ~[owlapi-osgidistribution.jar:4.2.
8-SNAPSHOT.2018-04-02T21:25:49Z]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.applyChanges(OWLOntologyManagerImpl.java:600) ~[owlapi-osgidistribution.jar:4.2.8-SNA
PSHOT.2018-04-02T21:25:49Z]
        at org.protege.editor.owl.client.action.EnableAutoUpdateAction$AutoUpdate.performUpdate(EnableAutoUpdateAction.java:188) ~[na:na]
        at org.protege.editor.owl.client.action.EnableAutoUpdateAction$AutoUpdate.run(EnableAutoUpdateAction.java:164) ~[na:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:1.8.0_102]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[na:1.8.0_102]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) ~[na:1.8.0_102]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_102]
        at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_102]

**Comment by NCIEVS** [comment]
Note from [EHD]:
"I can’t remember if we needed further documentation of the issue where an error is thrown and the text on the Description subtab of Edit tab turns pink, since this is just a minor annoyance. Although, being annoyed to the point of having to immediately log out and then log into a new instance may be enough to promote this to a medium priority issue. This just happened to me moments ago, so here is the error log text and the Thread Dump."

Attached file includes the text of the log file and the thread dump.  The log file shows a "level error" entry in line 443 (attached text file).  The error is different to the stack trace above.

Raising priority to medium.  Still in scope.

[pink-error-log.txt](https://github.com/NCIEVS/nci-protege5/files/4072068/pink-error-log.txt)

**Comment by NCIEVS** [comment]
Additional report from [EHD]:
"I had the display of the roles turn pink but in this case I was browsing and hadn’t edited in a while. So I am reporting this in case someone reports other (more serious) issues that they ran into today (6/23) between 2:15 and 2:30ish."

 A screenshot of the concept being edited at the time is in the original email ( June 23, 2020 2:37 PM).

The relevant exception seems to have happened at 2:32 PM 6/23/20.  The top of the stack trace is immediately below (and the same as in the previous comment).  However, there was another error, a null pointer exception, recorded 10 minutes earlier at 2:22 PM which could have been the trigger for the "stale view", and is the same as the exception in the original bug report, the top of this stack trace is further below.  

The zip of the protege log is attached.  (BTW, there are a number of warnings and exceptions elsewhere that should probably be put on the queue for triage.)

2020-06-23 14:32:35.150 [AWT-EventQueue-0] ERROR ProtegeApplication    Uncaught Exception in thread 'AWT-EventQueue-0'
javax.swing.text.StateInvariantError: GlyphView: Stale view: javax.swing.text.BadLocationException: Invalid location
	at javax.swing.text.GlyphView.getText(GlyphView.java:137) ~[na:1.8.0_212]
	at javax.swing.text.GlyphPainter1.getSpan(GlyphPainter1.java:60) ~[na:1.8.0_212]
	at javax.swing.text.GlyphView.getPreferredSpan(GlyphView.java:592) ~[na:1.8.0_212]
	at javax.swing.text.View.getMaximumSpan(View.java:268) ~[na:1.8.0_212]
	at javax.swing.text.ParagraphView.findEdgeSpan(ParagraphView.java:762) ~[na:1.8.0_212]
	at javax.swing.text.ParagraphView.calculateMinorAxisRequirements(ParagraphView.java:730) ~[na:1.8.0_212]
	at javax.swing.text.BoxView.checkRequests(BoxView.java:935) ~[na:1.8.0_212]
	at javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:343) ~[na:1.8.0_212]
	at javax.swing.text.BoxView.layout(BoxView.java:708) ~[na:1.8.0_212]
	at javax.swing.text.FlowView.layout(FlowView.java:220) ~[na:1.8.0_212]

2020-06-23 14:22:34.978 [AWT-EventQueue-0] ERROR ProtegeApplication    Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.NullPointerException: null
	at javax.swing.text.FlowView$FlowStrategy.createView(FlowView.java:663) ~[na:1.8.0_212]
	at javax.swing.text.FlowView$FlowStrategy.layoutRow(FlowView.java:520) ~[na:1.8.0_212]
	at javax.swing.text.FlowView$FlowStrategy.layout(FlowView.java:477) ~[na:1.8.0_212]
	at javax.swing.text.FlowView.layout(FlowView.java:201) ~[na:1.8.0_212]
	at javax.swing.text.BoxView.setSize(BoxView.java:397) ~[na:1.8.0_212]
	at javax.swing.text.BoxView.updateChildSizes(BoxView.java:366) ~[na:1.8.0_212]
	at javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:348) ~[na:1.8.0_212]
	at javax.swing.text.BoxView.layout(BoxView.java:708) ~[na:1.8.0_212]
	at javax.swing.text.BoxView.setSize(BoxView.java:397) ~[na:1.8.0_212]
	at javax.swing.plaf.basic.BasicTextUI$RootView.setSize(BasicTextUI.java:1722) ~[na:1.8.0_212]

[protege_log_L.zip](https://github.com/NCIEVS/nci-protege5/files/4838413/protege_log_L.zip)

**Comment by NCIEVS** [comment]
Looking at this one for next triage.  Have to wonder if it's related to autoupdate (so the fix to it could have ameliorated or eliminated this one already) as there were autoupdates received within microseconds of the exceptions above having been thrown. 

In any case, parking some search hits here re the exceptions, maybe they can be caught in the base protege code:
https://bugs.openjdk.java.net/browse/JDK-6818231
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4382539
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4362091
https://undocumentedmatlab.com/articles/bold-color-text-in-the-command-window
and of course, the array index out of bounds
https://docs.oracle.com/javase/7/docs/api/java/lang/ArrayIndexOutOfBoundsException.html
which is a runtime unchecked exception.

**Comment by bdionne** [comment]
Have we seen this since we removed the autoupdater?

These exceptions, are diff from the ones in the references, and are all coming from the `OWLCellRenderer`. Not sure what catching would do here other than to silence them. As noted, the GUI is still functional

**Comment by NCIEVS** [comment]
Ah yes, I missed this one, I'll ping [EHD].

The ```javax.swing.text.StateInvariantError: GlyphView: Stale view: javax.swing.text.BadLocationException``` appears above.  But looks like the same "flavor" as the outofbounds array exception.

But yes, if the exception gets thrown, the deed is done.

**Comment by NCIEVS** [comment]
Checked with the editors.  This hasn't been seen for some time.  Closing with "won't fix" (though it probably is).
