### ISSUE TITLE
reasoner error querying for the equivalent-properties of an object property

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#384]
This exception has been observed twice and involves axioms not used in the ncit.  The reasoner doesn't die and remains available.  Only the top of the stack trace (from [EHD]) is shown below:

INFO: Create schema reasoner with BUFFERING
No connection manager can be found
←[34mPre-computing inferences:←[0;39m
←[34m    - class hierarchy←[0;39m
←[34mOntologies processed in 102 ms by Pellet (Remote)←[0;39m
←[34m←[0;39m
Executed calls: 1
Total time to date on server: 3206
←[1;31mAn error occurred whilst asking the reasoner for the equivalent-properties of an object property: java.lang.RuntimeException: Request call fail
ed: [500] Internal Server Error←[0;39m
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: Request call failed: [500] Internal Server Error
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203) ~[guava.jar:na]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3937) ~[guava.jar:na]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941) ~[guava.jar:na]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824) ~[guava.jar:na]
        at com.complexible.pellet.client.reasoner.RemoteSchemaReasoner.query(RemoteSchemaReasoner.java:67) ~[na:na]
        at com.complexible.pellet.client.reasoner.SchemaOWLReasoner.executeQuery(SchemaOWLReasoner.java:121) ~[na:na]
        at com.complexible.pellet.client.reasoner.SchemaOWLReasoner.executeSingletonQuery(SchemaOWLReasoner.java:112) ~[na:na]
       at com.complexible.pellet.client.reasoner.SchemaOWLReasoner.getEquivalentObjectProperties(SchemaOWLReasoner.java:307) ~[na:na]

**Comment by NCIEVS** [comment]
[EHD} just ran into this exception again (6/15/18).  Raising priority a bit.

**Comment by bdionne** [comment]
Does it help to restrict the preferences to just the inferences you care about? I usually go for satisfiability and equivalent classes

**Comment by NCIEVS** [comment]
Applies to Pellet which is no longer being used.  Close.
