### ISSUE TITLE
Unable to Add Sub Classes in Protege Client 

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#391]
Unable to Add Sub Classes in Protege client when clicking on 'Add subclass' button from 'NCI Edit Tab'  , 

![image](https://user-images.githubusercontent.com/36314371/42578543-9648d33a-84f4-11e8-9bd8-798b7acf2f2c.png)

Error description Logs are  ::

[1;31mUncaught Exception in thread 'AWT-EventQueue-0'[0;39m
java.lang.NullPointerException: null
        at gov.nih.nci.ui.dialog.NCIClassCreationDialog.createDefinitionPanel(NCIClassCreationDialog.java:199) ~[na:na]
        at gov.nih.nci.ui.dialog.NCIClassCreationDialog.createUI(NCIClassCreationDialog.java:154) ~[na:na]
        at gov.nih.nci.ui.dialog.NCIClassCreationDialog.<init>(NCIClassCreationDialog.java:115) ~[na:na]
        at gov.nih.nci.ui.NCIEditTab.createNewChild(NCIEditTab.java:1259) ~[na:na]
        at gov.nih.nci.ui.NCIToldOWLClassHierarchyViewComponent.createNewChild(NCIToldOWLClassHierarchyViewComponent.java:367) ~[na:na]
        at gov.nih.nci.ui.NCIToldOWLClassHierarchyViewComponent$1.actionPerformed(NCIToldOWLClassHierarchyViewComponent.java:69) ~[na:na]
        at org.protege.editor.core.ui.view.ViewActionAdapter.actionPerformed(ViewActionAdapter.java:48) ~[na:na]
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source) ~[na:1.8.0_102]
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.processMouseEvent(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.JComponent.processMouseEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.processEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Container.processEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.dispatchEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Window.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.dispatchEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventQueue.access$500(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventQueue$3.run(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventQueue$3.run(Unknown Source) ~[na:1.8.0_102]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_102]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[na:1.8.0_102]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventQueue$4.run(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventQueue$4.run(Unknown Source) ~[na:1.8.0_102]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_102]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [na:1.8.0_102]
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [na:1.8.0_102]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [na:1.8.0_102]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_102]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_102]
        at java.awt.EventDispatchThread.run(Unknown Source) [na:1.8.0_102]

**Comment by singhik** [comment]
Just to add to above, Concept creation via Batch Load is also creating Java Null Pointer Exceptions  ::

![image](https://user-images.githubusercontent.com/36314371/42580300-3074cb78-84f8-11e8-819f-855c32c57012.png)

**Comment by NCIEVS** [comment]
This is related to #166.

**Comment by bdionne** [comment]
I'm pretty sure what this is is a bad `gencode` file in the protege server. If the sequence number is bad it tries to create classes that already exist. We should try detect this use case and provide a better message. @safrant could you please check that the `gencode` file is correct and copied over during the build?

**Comment by safrant** [comment]
I just checked and it is 1018, which is clearly wrong.  I updated it to 153065 (just past the last know Prod code). I haven't touched the ncitgencode since the previous round of testing and the concept creation was working then.

**Comment by safrant** [comment]
The problem with creating classes was not resolved by increasing the code in the code generator file.  I did some testing on Dev and on Stage and it is throwing the same errors that Itendra is seeing on QA.  Both of these projects were created in April and have been used for testing and creating concepts since.
 
I also tested QA using 2.4.0 and it was able to create concepts successfully.

I manually downloaded the revision-history-1.0.7.jar, in case the problem was a hook from creation into history, but it still does not work.

**Comment by bdionne** [comment]
[fixed in 0.8.6](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-0.8.6)

**Comment by safrant** [comment]
OK, this is working.  Itendra, this is a plugin only fix so you don't need a new client.

**Comment by singhik** [comment]
Creation of Sub-Classes and Save of Properties is working with Edit Tab plugin v0.8.6, hence closing this ticket ....
