### ISSUE TITLE
sparql plugin 2.0.8 fails to execute

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#392]
Tested with various queries in the github "bookmarks" folder, and it throws the following exception:  

←[1;31mAn error was thrown: java.lang.NullPointerException←[0;39m
org.protege.editor.owl.rdf.SparqlReasonerException: java.lang.NullPointerException
        at org.protege.editor.owl.rdf.repository.BasicSparqlReasoner.executeQuery(BasicSparqlReasoner.java:90) ~[na:na]
        at org.protege.editor.owl.rdf.SparqlQueryView$3.actionPerformed(SparqlQueryView.java:170) ~[na:na]
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) [na:1.8.0_102]
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) [na:1.8.0_102]
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) [na:1.8.0_102]
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source) [na:1.8.0_102]
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source) [na:1.8.0_102]
        at java.awt.Component.processMouseEvent(Unknown Source) [na:1.8.0_102]
        at javax.swing.JComponent.processMouseEvent(Unknown Source) [na:1.8.0_102]
        at java.awt.Component.processEvent(Unknown Source) [na:1.8.0_102]
        at java.awt.Container.processEvent(Unknown Source) [na:1.8.0_102]
        at java.awt.Component.dispatchEventImpl(Unknown Source) [na:1.8.0_102]
        at java.awt.Container.dispatchEventImpl(Unknown Source) [na:1.8.0_102]
        at java.awt.Component.dispatchEvent(Unknown Source) [na:1.8.0_102]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) [na:1.8.0_102]
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) [na:1.8.0_102]
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) [na:1.8.0_102]
        at java.awt.Container.dispatchEventImpl(Unknown Source) [na:1.8.0_102]
        at java.awt.Window.dispatchEventImpl(Unknown Source) [na:1.8.0_102]
        at java.awt.Component.dispatchEvent(Unknown Source) [na:1.8.0_102]
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [na:1.8.0_102]

**Comment by bdionne** [comment]
@NCIEVS  - I'm not sure what this is about, these run for me. If they all fail then I suspect something like a bad jar file or you don't have the current `2.0.8` plugin? When I was pushing the other day there were issues with uploading failing on my connection. 

I just pushed the jar for [sparql](https://github.com/NCIEVS/sparql-query-plugin/releases/tag/sparql-query-plugin-2.0.8) that runs fine for me. I recommend trying this one and see if it helps.

<img width="1016" alt="screen shot 2018-07-14 at 9 04 36 am" src="https://user-images.githubusercontent.com/31741/42717678-05d0735e-8746-11e8-8c01-8df44e1b2beb.png">

**Comment by NCIEVS** [comment]
The 2.0.9 plugin doesn't throw exceptions and returns the anticipated results.

**Comment by singhik** [comment]
QA has verified SPARQL Plugin 2.0.9 on Protege Client v 2.5.0 **working** with **no Exceptions** for 
Query Execution,Export and Bookmark operations, hence closing the ticket ...
