### ISSUE TITLE
null pointer exception on "complex" editing gui wedges protege

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#4]
I was attempting to do a complex edit (split), but what exactly threw the exception I can't say.  The editing panels ceased to update, the classes on the tree widget can't be highlighted although the tree nodes can be opened and navigated in the widget.  Going over to the classes tab, the editing panels get updated, but going back to the nciedittab you get one update on "comeback" but then stops updating.  The top of the stack trace was:

An error occurred whilst instantiating a menu action.
java.lang.NullPointerException: null
        at gov.nih.nci.ui.NCIEditTab.isSubClass(NCIEditTab.java:344) ~[na:na]
        at gov.nih.nci.ui.NCIEditTab.isPreRetired(NCIEditTab.java:331) ~[na:na]
        at gov.nih.nci.ui.NCIEditTab.canSplit(NCIEditTab.java:365) ~[na:na]
        at gov.nih.nci.ui.NCIToldOWLClassHierarchyViewComponent.canSplitClass(NCIToldOWLClassHierarchyViewComponent.java:131) ~[na:na]
        at gov.nih.nci.ui.action.SplitClassAction.canPerform(SplitClassAction.java:24) ~[na:na]
        at org.protege.editor.owl.ui.action.FocusedComponentAction.update(FocusedComponentAction.java:71) ~[na:na]
        at org.protege.editor.owl.ui.action.FocusedComponentAction.initialise(FocusedComponentAction.java:37) ~[na:na]
        at org.protege.editor.core.ui.menu.MenuActionPluginJPFImpl.newInstance(MenuActionPluginJPFImpl.java:169) [protege-editor-core.jar:na]
        at org.protege.editor.core.ui.menu.MenuActionPluginJPFImpl.newInstance(MenuActionPluginJPFImpl.java:31) [protege-editor-core.jar:na]
        at org.protege.editor.core.ui.menu.MenuBuilder.buildInnerMenu(MenuBuilder.java:159) [protege-editor-core.jar:na]
        at org.protege.editor.core.ui.menu.MenuBuilder.addMenu(MenuBuilder.java:114) [protege-editor-core.jar:na]
        at org.protege.editor.core.ui.menu.MenuBuilder.buildPopupMenu(MenuBuilder.java:95) [protege-editor-core.jar:na]
        at org.protege.editor.owl.ui.tree.OWLObjectTree.showPopupMenu(OWLObjectTree.java:189) [protege-editor-owl.jar:na]
        at org.protege.editor.owl.ui.tree.OWLObjectTree.access$100(OWLObjectTree.java:52) [protege-editor-owl.jar:na]
        at org.protege.editor.owl.ui.tree.OWLObjectTree$3.mousePressed(OWLObjectTree.java:142) [protege-editor-owl.jar:na]
        at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280) [na:1.8.0_92]

**Comment by bdionne** [comment]
much has changed since this, the stack trace is no longer relevant @NCIEVS just re-open id it occurs again
