### ISSUE TITLE
Clone Copy Intermittent Issue Protege (Not Reproducible)

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#449]
Editors have experienced issues while Clone(Copy) Concepts , their comments :: 

"Editors  have seen this issue both in 3.2.0 and 3.3.0 but it happens inconsistently, so I hadn’t reported it before. Now Editor has reported seeing this occur today, but again it was inconsistent. (She did several copy actions and the non-NCI FULL_SYN did not copy to the new concepts but then on the fifth or sixth try the behavior corrected itself.) I have seen this behavior both with FULL_SYN and Maps_To so it looks like a complex property issue but since there is no pattern I have seen, simple properties may not be immune. "

"Editors cloned 14 concepts and maybe 4 of them randomly (seemingly) copied over the Full Syns."

No File or List of concepts could be supplied nor their was an Exception Error Log that was Provided .

@singhik  Has tried to reproduce the error with a list of 10 concepts having Complex Properties(Full_Syn, Def,Alt-Def,Maps To) as well as Simple Properties, but **IS NOT** Reproducible. 
All the cloned concepts get the data copied successfully and in entirety . Attached is the screen print document of the same . This Test has been repeated in both 3.2.0 and 3.3.0 Protege Code Base .

[Clone_Copy_Protege.docx](https://github.com/NCIEVS/nci-protege5/files/4773036/Clone_Copy_Protege.docx)

**Comment by NCIEVS** [comment]
Attaching a zip of [TQ]'s log starting from the last entry on 6/11/20 through 9 AM 6/12/20.  The only thing I can see out of the ordinary is a listener dropping out at 7:58 AM involving the complex edit panel, recorded in two identical exceptions within milliseconds of each other.  The top of the first exception thrown at that time is here:
&nbsp;
2020-06-12 07:58:47.888 [AWT-EventQueue-0] WARN  OWLOntologyManagerImpl    BADLY BEHAVING LISTENER: null has been removed
java.lang.NullPointerException: null
	at org.protege.editor.owl.ui.frame.cls.OWLClassGeneralClassAxiomFrameSection.isResettingChange(OWLClassGeneralClassAxiomFrameSection.java:101) ~[protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at org.protege.editor.owl.ui.frame.AbstractOWLFrameSection.processOntologyChanges(AbstractOWLFrameSection.java:91) ~[protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at org.protege.editor.owl.ui.frame.AbstractOWLFrameSection.lambda$new$0(AbstractOWLFrameSection.java:53) ~[protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at org.semanticweb.owlapi.model.DefaultChangeBroadcastStrategy.broadcastChanges(DefaultChangeBroadcastStrategy.java:32) ~[owlapi-osgidistribution-5.1.6-SNAPSHOT.jar:5.1.6-SNAPSHOT.2020-04-24T18:53:44Z]
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.broadcastChanges(OWLOntologyManagerImpl.java:1530) [owlapi-osgidistribution-5.1.6-SNAPSHOT.jar:5.1.6-SNAPSHOT.2020-04-24T18:53:44Z]
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.applyChangesAndGetDetails(OWLOntologyManagerImpl.java:636) [owlapi-osgidistribution-5.1.6-SNAPSHOT.jar:5.1.6-SNAPSHOT.2020-04-24T18:53:44Z]
	at org.semanticweb.owlapi.model.HasApplyChanges.applyChanges(HasApplyChanges.java:37) [owlapi-osgidistribution-5.1.6-SNAPSHOT.jar:5.1.6-SNAPSHOT.2020-04-24T18:53:44Z]
	at org.protege.editor.owl.client.SessionRecorder.undo(SessionRecorder.java:195) [protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at gov.nih.nci.ui.NCIEditTab.undoChanges(NCIEditTab.java:1064) [nci-edit-tab-1.1.0.jar:na]
	at gov.nih.nci.ui.ComplexEditPanel$2.actionPerformed(ComplexEditPanel.java:206) [nci-edit-tab-1.1.0.jar:na]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) [na:1.8.0_212]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) [na:1.8.0_212]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) [na:1.8.0_212]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) [na:1.8.0_212]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) [na:1.8.0_212]
	at java.awt.Component.processMouseEvent(Component.java:6539) [na:1.8.0_212]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) [na:1.8.0_212


[protege-20200612AM.zip](https://github.com/NCIEVS/nci-protege5/files/4781522/protege-20200612AM.zip)

**Comment by singhik** [comment]
@bdionne @NCIEVS : Hi, Multiple iterations of the same have been performed on 3.5.0-QA1 built and the issue is still '**not reproducible**', hence closing the ticket .
