### ISSUE TITLE
fileprefs corruption - full syn table not populated

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#469]
From email on 9/14/2020 4:10 PM [NS]:
- Which operation failed? (such as Merge, Copy, Creation, PT changing)
I am not seeing FULL_SYNS
- Approximately what time did this failure occur?
3:45PM September 14, 2020
- Description or sequence of steps followed:
- Concepts involved:
- If necessary, please include the state that the concepts were in at the time of the incident (e.g. edits of roles, defined/primitive changes). Screenshot is good if possible.
- Outcome (screen frozen, concept not created, had to log out and in to get things to work better):
We are going to remove the file prefs<< ATT47385.fileprefs >> << protege.zip >>
- Attach log if possible (usually in current Protégé folder, in  .protege, logs) (Please zip the log folder and attach to this email)

**Comment by NCIEVS** [comment]
From log file (not attached), the only exception for 9/14 happened at 3:27 pm:

2020-09-14 15:27:50.708 [AWT-EventQueue-0] WARN  OWLOntologyManagerImpl    BADLY BEHAVING LISTENER: null has been removed
java.lang.NullPointerException: null
	at org.protege.editor.owl.ui.frame.cls.OWLClassGeneralClassAxiomFrameSection.isResettingChange(OWLClassGeneralClassAxiomFrameSection.java:101) ~[protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at org.protege.editor.owl.ui.frame.AbstractOWLFrameSection.processOntologyChanges(AbstractOWLFrameSection.java:91) ~[protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at org.protege.editor.owl.ui.frame.AbstractOWLFrameSection.lambda$new$0(AbstractOWLFrameSection.java:53) ~[protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at org.semanticweb.owlapi.model.DefaultChangeBroadcastStrategy.broadcastChanges(DefaultChangeBroadcastStrategy.java:32) ~[owlapi-osgidistribution-5.1.6-SNAPSHOT.jar:5.1.6-SNAPSHOT.2020-04-24T18:53:44Z]
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.broadcastChanges(OWLOntologyManagerImpl.java:1530) [owlapi-osgidistribution-5.1.6-SNAPSHOT.jar:5.1.6-SNAPSHOT.2020-04-24T18:53:44Z]
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.applyChangesAndGetDetails(OWLOntologyManagerImpl.java:636) [owlapi-osgidistribution-5.1.6-SNAPSHOT.jar:5.1.6-SNAPSHOT.2020-04-24T18:53:44Z]
	at org.semanticweb.owlapi.model.HasApplyChanges.applyChanges(HasApplyChanges.java:37) [owlapi-osgidistribution-5.1.6-SNAPSHOT.jar:5.1.6-SNAPSHOT.2020-04-24T18:53:44Z]
	at org.protege.editor.owl.client.SessionRecorder.undo(SessionRecorder.java:195) [protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at gov.nih.nci.ui.NCIEditTab.undoChanges(NCIEditTab.java:1064) [nci-edit-tab-1.1.0.jar:na]
	at gov.nih.nci.ui.EditPanel$5.actionPerformed(EditPanel.java:401) [nci-edit-tab-1.1.0.jar:na]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) [na:1.8.0_212]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) [na:1.8.0_212]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) [na:1.8.0_212]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) [na:1.8.0_212]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) [na:1.8.0_212]
	at java.awt.Component.processMouseEvent(Component.java:6539) [na:1.8.0_212]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) [na:1.8.0_212]
	at java.awt.Component.processEvent(Component.java:6304) [na:1.8.0_212]
	at java.awt.Container.processEvent(Container.java:2239) [na:1.8.0_212]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) [na:1.8.0_212]
	at java.awt.Container.dispatchEventImpl(Container.java:2297) [na:1.8.0_212]
	at java.awt.Component.dispatchEvent(Component.java:4711) [na:1.8.0_212]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904) [na:1.8.0_212]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535) [na:1.8.0_212]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476) [na:1.8.0_212]
	at java.awt.Container.dispatchEventImpl(Container.java:2283) [na:1.8.0_212]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) [na:1.8.0_212]
	at java.awt.Component.dispatchEvent(Component.java:4711) [na:1.8.0_212]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760) [na:1.8.0_212]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [na:1.8.0_212]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [na:1.8.0_212]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [na:1.8.0_212]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_212]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) [na:1.8.0_212]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84) [na:1.8.0_212]
	at java.awt.EventQueue$4.run(EventQueue.java:733) [na:1.8.0_212]
	at java.awt.EventQueue$4.run(EventQueue.java:731) [na:1.8.0_212]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_212]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) [na:1.8.0_212]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730) [na:1.8.0_212]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [na:1.8.0_212]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_212]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_212]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_212]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_212]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_212]

**Comment by cmoid** [comment]
@NCIEVS Would it be possible for Nick to provide more information? I was thus yesterday, and the exception, and it's not clear form the log what he was doing. Did this happen after and edit? Running the classifier? OR just browsing after opening?

**Comment by NCIEVS** [comment]
The value-less full_syn table display can be observed with the attached .fileprefs from the bug report.  This matches the value-less properties in the fileprefs, for instance:

PROTEGE_PREFERENCES/application_preferences/class\ gov.nih.nci.ui.PropertyTableModelFULL_SYN/FULL_SYN/4=

Other than this, the only thing that I can pick up from visual inspection is a corrupted key, at line 48, which starts with:

g.protege.editor.owl.OWLAnnotationPropertyAnnotations

(the "or" in "org" appears to have been dropped).


[ns-20200914.fileprefs.txt](https://github.com/NCIEVS/nci-protege5/files/5225119/ns-20200914.fileprefs.txt)

**Comment by NCIEVS** [comment]
From follow up with [NS]:
"I was trying to create the new term Tumor Classification under Classification. While I could see the added definition, I could not see the added PT and synonym. I was worried and I cleared the edit and asked Terry to create this term. Then, I started checking cancer terms and I noticed that the PTs and the synonyms were absent in my protégé version."

**Comment by bdionne** [comment]
Thanks @NCIEVS - I can see all the fileprefs stuff and log files, it's the user scenario that's the most valuable as it allows me to try and reproduce it. For example the log indicated that he did an `undo`, which the follow up confirms.

This attached fileprefs is different form the one that came from the report. Is it from you machine? The date is a day earlier.

**Comment by singhik** [comment]
[Protege_Full-Syn.docx](https://github.com/NCIEVS/nci-protege5/files/5234458/Protege_Full-Syn.docx)

**Comment by singhik** [comment]
Not reproducible , Build 3.5.0-qa1, NCI EDIT PLUGIN 1.1.9, hence closed

**Comment by bdionne** [comment]
@singhik I think that 1.1.9 `EditTab` also fixed this.
