### ISSUE TITLE
Permissions issue throws inscrutable error

### ISSUE THREAD

**Issue by safrant** [NCIEVS/nci-protege5#517]
Tag 3.7.0-qa1.  When logging on with a user that does not have modeling permissions, the protege client throws an inscrutable painter error rather than a permissions error. 

1. Set up a user with only the Administrator role
2. With that user, open protege client and choose "Open from Protege Server" and connect with a server running 3.7.0 (Dev, in this case)
3.  Select any project and open.  It will go through the motions of opening the project and will create a project folder locally.  At the last it will throw a painter error and fail.  (see below for stack trace)
4. Log out, close protege.  
5. Using admin gui, give the user Workflow_Modeler role. Save and close
6.  Open protege client, choose "Open from Protege Server" and select a project
7. The project will open without error

While the behavior of the application is appropriate, the error thrown is difficult to parse.  It does not indicate that the issue is tied to permissions.  Please wrap this error or handle it in a way that is easier to understand.

2021-06-28 10:15:05.983 [AWT-EventQueue-0] ERROR ProtegeApplication    Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.ArrayIndexOutOfBoundsException: -1
	at javax.swing.plaf.basic.BasicTabbedPaneUI.getTabBounds(BasicTabbedPaneUI.java:1534) ~[na:1.8.0_291]
	at javax.swing.plaf.basic.BasicTabbedPaneUI.getTabBounds(BasicTabbedPaneUI.java:1469) ~[na:1.8.0_291]
	at org.protege.editor.core.ui.tabbedpane.CloseableTabbedPaneUI.getTabBounds(CloseableTabbedPaneUI.java:266) ~[protege-editor-core-5.1.2-SNAPSHOT.jar:na]
	at org.protege.editor.core.ui.tabbedpane.CloseableTabbedPaneUI.paintContentBorderTopEdge(CloseableTabbedPaneUI.java:397) ~[protege-editor-core-5.1.2-SNAPSHOT.jar:na]
	at javax.swing.plaf.basic.BasicTabbedPaneUI.paintContentBorder(BasicTabbedPaneUI.java:1315) ~[na:1.8.0_291]
	at javax.swing.plaf.basic.BasicTabbedPaneUI.paint(BasicTabbedPaneUI.java:791) ~[na:1.8.0_291]
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161) ~[na:1.8.0_291]
	at javax.swing.JComponent.paintComponent(JComponent.java:780) ~[na:1.8.0_291]
	at javax.swing.JComponent.paint(JComponent.java:1056) ~[na:1.8.0_291]
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210) ~[na:1.8.0_291]
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579) ~[na:1.8.0_291]
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502) ~[na:1.8.0_291]
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272) ~[na:1.8.0_291]
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158) ~[na:1.8.0_291]
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969) ~[na:1.8.0_291]
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831) ~[na:1.8.0_291]
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814) ~[na:1.8.0_291]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_291]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) ~[na:1.8.0_291]
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814) ~[na:1.8.0_291]
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789) ~[na:1.8.0_291]
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738) ~[na:1.8.0_291]
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64) ~[na:1.8.0_291]
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732) ~[na:1.8.0_291]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[na:1.8.0_291]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[na:1.8.0_291]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_291]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[na:1.8.0_291]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[na:1.8.0_291]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_291]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) ~[na:1.8.0_291]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[na:1.8.0_291]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [na:1.8.0_291]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_291]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_291]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_291]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_291]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_291]

**Comment by singhik** [comment]
@bdionne @NCIEVS : Hi, Error logs do not indicate any mentioning of the Admin user not having appropriate permissions to login to a project, so what actually has been changed in the Log verbiage ?? Below is the log trace when a 'admin' only user accesses a Project .



[Logs.txt](https://github.com/NCIEVS/nci-protege5/files/9455685/Logs.txt)

**Comment by singhik** [comment]
@bdionne @NCIEVS :  Hi, Not sure about the implementation of this ticket , questions below : 

> A 'admin' only user has 'open-project' tied to it, so why will he be not able to login to a Project  ? 

I did a trial of a 'admin' only user and was able to login to a project 

![image](https://user-images.githubusercontent.com/36314371/187518496-f9d14b0c-64c0-4a8a-a082-d527daec2c2b.png)

User 'singhAdmin' , able to login to a project without any errors : 

![image](https://user-images.githubusercontent.com/36314371/187518322-38729d93-c0a5-49c3-9a6f-11d7db1b8427.png)

**Comment by bdionne** [comment]
@singhik That was the bug (see the steps to reproduce above). Tracy had a user that only had Administrator role, and was unable to open project (she got the exception above). When she added another role it fixed it. You were able to open the project, which it should allow.

So it's fixed :)

**Comment by singhik** [comment]
@bdionne  @safrant  : Hi Bob, i think this issue was raised to correct the Error verbiage to indicate the reason for a user not being able to login i.e. an Admin only user is not allowed to login to a Project and the respective error should state that reasoning. Please review the steps from @safrant .

**Comment by bdionne** [comment]
not so @singhik, an Administrator user can indeed open a project:

> Set up a user with only the Administrator role
