### ISSUE TITLE
Classification after reparenting across domains leaves protege in bad state

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#524]
I re-treed a defined concept from the "gene" to the "experimental organism diagnosis" domain (concept C178195 was retreed under C22187), with the curator check on retreeing disabled.  After classification I went to enable the inferences panel and started getting the same exception wherever I clicked (below).  But protege was at that point not responding properly to the clicks, and couldn't continue editing.  Was done with the 3.6.0 UAT vocabulary in Stage.  Restored the C178195 to its initial location, and reproduced the issue after the same re-treeing operation.

2021-08-05 17:00:37.289 [Classification Thread] INFO  RolesVisitor    Role: R130 has domain C16612 and can't be used on class C178195
2021-08-05 17:00:37.289 [Classification Thread] INFO  RolesVisitor    Role: R130 has domain C16612 and can't be used on class C178195
2021-08-05 17:00:37.289 [Classification Thread] INFO  RolesVisitor    Role: R130 has domain C16612 and can't be used on class C178195
2021-08-05 17:00:37.289 [Classification Thread] INFO  RolesVisitor    Role: R40 has domain C16612 and can't be used on class C178195
broadcasting again
2021-08-05 17:04:24.880 [AWT-EventQueue-0] ERROR ProtegeApplication    Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.NullPointerException: null
	at org.protege.editor.owl.ui.renderer.OWLObjectRendererImpl.render(OWLObjectRendererImpl.java:58) ~[protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at org.protege.editor.owl.model.cache.OWLObjectRenderingCache.getRendering(OWLObjectRenderingCache.java:57) ~[protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at org.protege.editor.owl.model.OWLModelManagerImpl.getRendering(OWLModelManagerImpl.java:853) ~[protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at org.protege.editor.owl.ui.frame.AbstractOWLFrameSectionRow.getObjectRendering(AbstractOWLFrameSectionRow.java:266) ~[protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at org.protege.editor.owl.ui.frame.AbstractOWLFrameSectionRow.getRendering(AbstractOWLFrameSectionRow.java:285) ~[protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at gov.nih.nci.ui.UnsupportedConstructsFrameSectionRow.getRendering(UnsupportedConstructsFrameSectionRow.java:59) ~[nci-edit-tab-1.2.9.1.jar:na]
	at org.protege.editor.owl.ui.framelist.OWLFrameListRenderer.getValueToRender(OWLFrameListRenderer.java:207) ~[protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at org.protege.editor.owl.ui.framelist.OWLFrameListRenderer.getListCellRendererComponent(OWLFrameListRenderer.java:159) ~[protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at org.protege.editor.core.ui.list.MList$MListCellRenderer.getListCellRendererComponent(MList.java:267) ~[protege-editor-core-5.1.2-SNAPSHOT.jar:na]
	at org.protege.editor.owl.ui.framelist.OWLFrameList$OWLFrameListUI.updateLayoutState(OWLFrameList.java:955) ~[protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1311) ~[na:1.8.0_292]
	at javax.swing.plaf.basic.BasicListUI.getPreferredSize(BasicListUI.java:578) ~[na:1.8.0_292]
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662) ~[na:1.8.0_292]
	at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791) ~[na:1.8.0_292]
	at java.awt.Container.layout(Container.java:1513) ~[na:1.8.0_292]
	at java.awt.Container.doLayout(Container.java:1502) ~[na:1.8.0_292]
	at java.awt.Container.validateTree(Container.java:1698) ~[na:1.8.0_292]
	at java.awt.Container.validateTree(Container.java:1707) ~[na:1.8.0_292]
	at java.awt.Container.validateTree(Container.java:1707) ~[na:1.8.0_292]
	at java.awt.Container.validateTree(Container.java:1707) ~[na:1.8.0_292]
	at java.awt.Container.validateTree(Container.java:1707) ~[na:1.8.0_292]
	at java.awt.Container.validateTree(Container.java:1707) ~[na:1.8.0_292]
	at java.awt.Container.validateTree(Container.java:1707) ~[na:1.8.0_292]
	at java.awt.Container.validateTree(Container.java:1707) ~[na:1.8.0_292]
	at java.awt.Container.validateTree(Container.java:1707) ~[na:1.8.0_292]
	at java.awt.Container.validateTree(Container.java:1707) ~[na:1.8.0_292]
	at java.awt.Container.validateTree(Container.java:1707) ~[na:1.8.0_292]
	at java.awt.Container.validate(Container.java:1633) ~[na:1.8.0_292]
	at javax.swing.RepaintManager$3.run(RepaintManager.java:711) ~[na:1.8.0_292]
	at javax.swing.RepaintManager$3.run(RepaintManager.java:709) ~[na:1.8.0_292]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_292]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) ~[na:1.8.0_292]
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708) ~[na:1.8.0_292]
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731) ~[na:1.8.0_292]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[na:1.8.0_292]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[na:1.8.0_292]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_292]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[na:1.8.0_292]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[na:1.8.0_292]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_292]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) ~[na:1.8.0_292]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[na:1.8.0_292]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [na:1.8.0_292]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_292]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_292]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_292]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_292]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_292]
LOGBACK: No context given for org.protege.editor.core.log.LogManager$1[null]
2021-08-05 17:04:24.883 [AWT-EventQueue-0] ERROR ProtegeApplication    Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.NullPointerException: null
	at org.protege.editor.owl.ui.renderer.OWLObjectRendererImpl.render(OWLObjectRendererImpl.java:58) ~[protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at org.protege.editor.owl.model.cache.OWLObjectRenderingCache.getRendering(OWLObjectRenderingCache.java:57) ~[protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at org.protege.editor.owl.model.OWLModelManagerImpl.getRendering(OWLModelManagerImpl.java:853) ~[protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at org.protege.editor.owl.ui.frame.AbstractOWLFrameSectionRow.getObjectRendering(AbstractOWLFrameSectionRow.java:266) ~[protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at org.protege.editor.owl.ui.frame.AbstractOWLFrameSectionRow.getRendering(AbstractOWLFrameSectionRow.java:285) ~[protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at gov.nih.nci.ui.UnsupportedConstructsFrameSectionRow.getRendering(UnsupportedConstructsFrameSectionRow.java:59) ~[nci-edit-tab-1.2.9.1.jar:na]
	at org.protege.editor.owl.ui.framelist.OWLFrameListRenderer.getValueToRender(OWLFrameListRenderer.java:207) ~[protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at org.protege.editor.owl.ui.framelist.OWLFrameListRenderer.getListCellRendererComponent(OWLFrameListRenderer.java:159) ~[protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at org.protege.editor.core.ui.list.MList$MListCellRenderer.getListCellRendererComponent(MList.java:267) ~[protege-editor-core-5.1.2-SNAPSHOT.jar:na]
	at org.protege.editor.owl.ui.framelist.OWLFrameList$OWLFrameListUI.updateLayoutState(OWLFrameList.java:955) ~[protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1311) ~[na:1.8.0_292]
	at javax.swing.plaf.basic.BasicListUI.getPreferredSize(BasicListUI.java:578) ~[na:1.8.0_292]
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662) ~[na:1.8.0_292]
	at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791) ~[na:1.8.0_292]

**Comment by bdionne** [comment]
This was already run into locally and [fixed](https://github.com/NCIEVS/nci-edit-tab/commit/f2229a5f42ed2b03719ab0bd3f7bb41d29c72749) in the next EditTab

**Comment by bdionne** [comment]
fixed in [1.3.0](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-1.3.0)

**Comment by singhik** [comment]
@NCIEVS : Hi, how did you re-tree a defined concept as defined concepts can not have a Sub Class axiom ?
did you first convert it to primitive, added the subclass(retree'd) and then converted back to defined ?

**Comment by NCIEVS** [comment]
@singhik , yes, you need to make it primitive, edit the parent, and then make it defined again.  You'll need to disable some of the curator's edit checks or you might not be able to edit the parent.  You can probably test with the same concept I used above.

**Comment by singhik** [comment]
@NCIEVS @bdionne : Hi, 

1. I am able to perform reparenting ,edits and curator runs (by disabling Checking some dependencies when retree to disjoint domains)  without Protege Hanging  . 
2. The INFO message which @NCIEVS  posted,  i do get that message in Protege logs, but that is post classification completion (expected), i don't get it everytime i do other operations in Editor .
3. I also get a Null Pointer Exception in the log, this exception is not impacting my Editor or Editing operations, but not sure if a null pointer is expected . I have attached the logs for @bdionne  to confirm .

[null-pointer-exception.txt](https://github.com/NCIEVS/nci-protege5/files/7003086/null-pointer-exception.txt)

**Comment by cmoid** [comment]
@singhik that null pointer is harmless, but I'll look at it. I meant to do it before as Liz also saw it. It just means your classification failed so there are no inferred results to show. We should probably prevent that call from being made in that case.
