### ISSUE TITLE
Logging out of ServerAdministration GUI throws exception

### ISSUE THREAD

**Issue by fragosog** [NCIEVS/nci-protege5#560]
Closing the ServerAdministration GUI after a session works fine.  But if you instead log out of the session via "Server -> Logout", you get an exception.  The top of the stack trace:

java.lang.NullPointerException
	at gov.nih.nci.client.admin.ui.JsonSerializationPanel.initUi(JsonSerializationPanel.java:53)
	at gov.nih.nci.client.admin.ui.JsonSerializationPanel.lambda$1(JsonSerializationPanel.java:72)
	at org.protege.editor.owl.client.ClientSession.fireChangeEvent(ClientSession.java:90)
	at org.protege.editor.owl.client.ClientSession.clear(ClientSession.java:195)
	at org.protege.editor.owl.client.util.ClientUtils.performLogout(ClientUtils.java:75)
	at org.protege.editor.owl.client.action.LogoutAction.actionPerformed(LogoutAction.java:37)

If after logging out as above you start an editing session (using a different user with workflow modeler/manager role) without restarting protege, edits are allowed to go in but the Save button is not enabled and they don't show up in the "Server ->  Show uncommitted changes".  The changes are not committed/persisted and they don't show up in a subsequent editing session.

**Comment by singhik** [comment]
Tested on 4.2.0-dev1 build , no Exceptions are thrown on Server Administrator GUI when Server->logout option is used .
