### ISSUE TITLE
Reading the unsquashed archive fails

### ISSUE THREAD

**Issue by fragosog** [NCIEVS/nci-protege5#567]
Copying the directory with the unsquashed history & history-snapshot from the archive to the server-side directory and editing the server config file to include the new project is not working.  The project is seen by the client, but when loading the project an exception (further below) is thrown from the client after "building versioned ontology" in the progress bar.  The "open project error" dialog pops up with the message "failed to read data from server."  The server doesn't throw an exception.  

(Should the archive nowadays include a checksum?  Also the codegen file even if not used?)

2023-03-14 12:07:03.759 [SwingWorker-pool-2-thread-1] ERROR LocalHttpClient    null
java.io.EOFException: null
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3111) ~[na:1.8.0_362]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1620) ~[na:1.8.0_362]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503) ~[na:1.8.0_362]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461) ~[na:1.8.0_362]
	at org.protege.editor.owl.client.LocalHttpClient.retrieveDocumentSnapshotFromServerResponse(LocalHttpClient.java:704) [protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at org.protege.editor.owl.client.LocalHttpClient.getSnapShot(LocalHttpClient.java:695) [protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at org.protege.editor.owl.client.LocalHttpClient.buildVersionedOntology(LocalHttpClient.java:577) [protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at org.protege.editor.owl.client.ui.OpenFromServerPanel.openOntologyDocument(OpenFromServerPanel.java:241) [protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at org.protege.editor.owl.client.ui.OpenFromServerPanel$OpenActionListener$1LoadDBWorker.doInBackground(OpenFromServerPanel.java:190) [protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at org.protege.editor.owl.client.ui.OpenFromServerPanel$OpenActionListener$1LoadDBWorker.doInBackground(OpenFromServerPanel.java:181) [protege-editor-owl-5.1.2-SNAPSHOT.jar:na]

**Comment by bdionne** [comment]
fixed in [4.3.0-dev1](https://github.com/NCIEVS/protege/tree/4.3.0-dev1) - requires server build

**Comment by chaozhang-nci** [comment]
tested with project Recap-Unsquashed-20230313 at the QA server.
